
INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '1',
    'Jeanne',
    'f',
    '1946-08-27',
    'Troubles addictifs',
    '2021-01-12',
    '72'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '2',
    'Patrick',
    'm',
    '1962-11-12',
    'Cancer bronchopulmonaire',
    '2021-02-03',
    '75'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '3',
    'Antoine',
    'm',
    '1930-08-13',
    'Mucoviscidose',
    '2022-03-12',
    '15'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '4',
    'Clément',
    'm',
    '1985-04-08',
    'Maladies inflammatoires chroniques',
    '2022-10-21',
    '64'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '5',
    'Enzo',
    'm',
    '1993-05-16',
    'Maladies inflammatoires chroniques',
    '2022-07-04',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '6',
    'Lucas',
    'm',
    '1997-07-21',
    'Cancer colorectal',
    '2023-02-26',
    '65'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '7',
    'Hajar',
    'f',
    '1931-10-08',
    'Cancer du sein de la femme',
    '2023-08-23',
    '27'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '8',
    'Ethan',
    'm',
    '2001-08-12',
    'Maladie de Parkinson',
    '2022-03-26',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '9',
    'Jean-Luc',
    'm',
    '1967-06-16',
    'Troubles psychotiques',
    '2023-02-01',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '10',
    'Mehdi',
    'm',
    '2000-12-30',
    'Polyarthrite rhumatoïde ',
    '2021-11-02',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '11',
    'Olivier',
    'm',
    '1974-04-29',
    'Cancer bronchopulmonaire',
    '2021-03-29',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '12',
    'Nassim',
    'm',
    '1979-11-14',
    'Cancer de la prostate',
    '2023-06-30',
    '87'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '13',
    'Yves',
    'm',
    '1934-11-21',
    'Cancer bronchopulmonaire',
    '2023-04-26',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '14',
    'Édith',
    'f',
    '1937-06-24',
    'Cancer de la prostate',
    '2023-04-22',
    '59'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '15',
    'Yvette',
    'f',
    '1925-01-24',
    'Troubles addictifs',
    '2023-06-15',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '16',
    'Nicole',
    'f',
    '1964-06-02',
    'Troubles psychotiques',
    '2023-10-26',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '17',
    'Kylian',
    'm',
    '2009-05-10',
    'Troubles addictifs',
    '2021-10-02',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '18',
    'Joseph',
    'm',
    '1959-07-09',
    'Maladies rares',
    '2021-04-05',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '19',
    'Hicham',
    'm',
    '2008-07-28',
    'Cancer bronchopulmonaire',
    '2021-11-30',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '20',
    'Idriss',
    'm',
    '2013-12-04',
    'Maladie de Parkinson',
    '2021-05-16',
    '45'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '21',
    'Mounir',
    'm',
    '1999-09-18',
    'Embolie pulmonaire',
    '2022-06-26',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '22',
    'Jacques',
    'm',
    '1940-02-17',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-10-01',
    '75'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '23',
    'Paul',
    'm',
    '1989-01-22',
    'Insuffisance cardiaque',
    '2022-01-22',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '24',
    'Florent',
    'm',
    '1984-05-25',
    'Cancer du sein de la femme',
    '2021-04-15',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '25',
    'Benoît',
    'm',
    '1978-05-11',
    'Embolie pulmonaire',
    '2022-05-05',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '26',
    'Adam',
    'm',
    '2005-08-09',
    'Accident vasculaire cérébral',
    '2021-10-30',
    '76'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '27',
    'Henry',
    'm',
    '1952-08-08',
    'Insuffisance cardiaque',
    '2022-01-07',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '28',
    'Camila',
    'f',
    '1996-08-27',
    'Accident vasculaire cérébral',
    '2022-10-30',
    '46'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '29',
    'Connor',
    'm',
    '1983-12-03',
    'Cancer bronchopulmonaire',
    '2023-11-02',
    '43'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '30',
    'Gilles',
    'm',
    '1952-08-06',
    'Polyarthrite rhumatoïde ',
    '2021-09-13',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '31',
    'Catherine',
    'f',
    '1969-06-07',
    'Cancer du sein de la femme',
    '2021-05-06',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '32',
    'Hélène',
    'f',
    '1938-09-29',
    'Maladie valvulaire',
    '2023-01-06',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '33',
    'Isabelle',
    'f',
    '1938-07-04',
    'Embolie pulmonaire',
    '2021-10-19',
    '31'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '34',
    'David',
    'm',
    '1991-10-06',
    'Cancer bronchopulmonaire',
    '2021-10-20',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '35',
    'Kamel',
    'm',
    '1997-10-06',
    'Maladie valvulaire',
    '2021-05-11',
    '33'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '36',
    'Evan',
    'm',
    '2001-09-24',
    'Polyarthrite rhumatoïde ',
    '2023-04-28',
    '67'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '37',
    'Jean-Michel',
    'm',
    '1925-03-31',
    'Maladies rares',
    '2022-01-14',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '38',
    'Gaspard',
    'm',
    '1943-02-05',
    'Troubles psychotiques',
    '2022-04-12',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '39',
    'Estelle',
    'f',
    '2002-08-12',
    'Embolie pulmonaire',
    '2022-04-10',
    '56'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '40',
    'Holly',
    'f',
    '1992-11-05',
    'Cancer de la prostate',
    '2023-02-10',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '41',
    'François',
    'm',
    '1930-04-29',
    'Accident vasculaire cérébral',
    '2021-01-10',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '42',
    'Jacob',
    'm',
    '1975-10-27',
    'Myopathie ou myasthénie',
    '2022-03-02',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '43',
    'Denise',
    'f',
    '1959-08-26',
    'Troubles addictifs',
    '2021-04-22',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '44',
    'Ibrahim',
    'm',
    '2002-05-06',
    'Cancer bronchopulmonaire',
    '2021-12-23',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '45',
    'Charlie',
    'm',
    '1972-03-10',
    'Embolie pulmonaire',
    '2022-08-13',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '46',
    'Baptiste',
    'm',
    '1951-03-11',
    'Cancer colorectal',
    '2021-08-22',
    '75'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '47',
    'Caoimhe',
    'f',
    '1942-02-10',
    'Maladies rares',
    '2023-07-05',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '48',
    'Edouard',
    'm',
    '1932-01-04',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-15',
    '49'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '49',
    'Véronique',
    'f',
    '1944-01-06',
    'Cancer bronchopulmonaire',
    '2021-10-09',
    '72'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '50',
    'Margaux',
    'f',
    '1978-10-08',
    'Cancer du sein de la femme',
    '2021-01-03',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '51',
    'Oscar',
    'm',
    '1994-09-06',
    'Cancer bronchopulmonaire',
    '2022-03-28',
    '48'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '52',
    'Martial',
    'm',
    '1965-10-16',
    'Mucoviscidose',
    '2021-08-27',
    '92'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '53',
    'Khalil',
    'm',
    '1962-12-19',
    'Troubles addictifs',
    '2021-08-13',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '54',
    'Stéphanie',
    'f',
    '1979-01-07',
    'Cancer du sein de la femme',
    '2023-08-14',
    '85'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '55',
    'Lionel',
    'm',
    '1981-03-28',
    'Troubles psychotiques',
    '2021-12-20',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '56',
    'Léna',
    'f',
    '1944-03-16',
    'Myopathie ou myasthénie',
    '2021-06-28',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '57',
    'Maël',
    'm',
    '1990-06-04',
    'Troubles addictifs',
    '2023-04-25',
    '08'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '58',
    'Madison',
    'f',
    '1995-06-23',
    'Maladie de Parkinson',
    '2022-05-04',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '59',
    'Malik',
    'm',
    '1976-08-31',
    'Cancer du sein de la femme',
    '2023-06-19',
    '55'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '60',
    'Julien',
    'm',
    '2006-08-22',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-18',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '61',
    'Nabil',
    'm',
    '1999-07-14',
    'Accident vasculaire cérébral',
    '2022-11-14',
    '27'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '62',
    'Rania',
    'f',
    '1997-11-17',
    'Maladie valvulaire',
    '2022-06-07',
    '56'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '63',
    'Sean',
    'm',
    '1974-06-15',
    'Diabète',
    '2021-09-18',
    '40'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '64',
    'Marceau',
    'm',
    '1988-11-18',
    'Cancer de la prostate',
    '2023-02-06',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '65',
    'Corentin',
    'm',
    '2001-10-25',
    'Maladie de Parkinson',
    '2022-04-19',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '66',
    'Gérard',
    'm',
    '1936-09-01',
    'Diabète',
    '2023-08-17',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '67',
    'Cécile',
    'f',
    '1959-04-29',
    'Embolie pulmonaire',
    '2023-08-14',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '68',
    'Gisèle',
    'f',
    '1931-12-19',
    'Accident vasculaire cérébral',
    '2023-11-17',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '69',
    'Jonathan',
    'm',
    '1932-01-17',
    'Cancer de la prostate',
    '2022-03-31',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '70',
    'Xavier',
    'm',
    '1925-08-13',
    'Troubles addictifs',
    '2021-08-06',
    '79'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '71',
    'Nadir',
    'm',
    '1994-05-03',
    'Insuffisance cardiaque',
    '2021-03-01',
    '84'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '72',
    'Laure',
    'f',
    '2015-04-24',
    'Cancer du sein de la femme',
    '2023-08-20',
    '972'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '73',
    'Mounia',
    'm',
    '1947-03-19',
    'Cancer de la prostate',
    '2021-11-30',
    '92'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '74',
    'Scarlett',
    'f',
    '1988-07-30',
    'Cancer du sein de la femme',
    '2022-07-17',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '75',
    'Darragh',
    'm',
    '1968-06-16',
    'Polyarthrite rhumatoïde ',
    '2021-01-04',
    '55'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '76',
    'Fatima',
    'f',
    '1963-10-24',
    'Troubles psychotiques',
    '2023-12-03',
    '45'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '77',
    'Dylan',
    'm',
    '1971-08-27',
    'Embolie pulmonaire',
    '2022-06-17',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '78',
    'Leo',
    'm',
    '2003-11-04',
    'Polyarthrite rhumatoïde ',
    '2022-07-22',
    '43'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '79',
    'Mathieu',
    'm',
    '1951-08-01',
    'Maladies inflammatoires chroniques',
    '2022-06-01',
    '67'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '80',
    'Liliane',
    'f',
    '1952-02-09',
    'Cancer bronchopulmonaire',
    '2022-08-20',
    '44'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '81',
    'Nova',
    'f',
    '1963-06-16',
    'Maladies rares',
    '2022-09-01',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '82',
    'Nour',
    'm',
    '1981-08-14',
    'Myopathie ou myasthénie',
    '2022-08-06',
    '22'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '83',
    'Marine',
    'f',
    '1980-10-03',
    'Polyarthrite rhumatoïde ',
    '2021-05-29',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '84',
    'Loïc',
    'm',
    '2008-11-22',
    'Accident vasculaire cérébral',
    '2021-03-09',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '85',
    'Jade',
    'f',
    '2001-02-08',
    'Myopathie ou myasthénie',
    '2021-04-29',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '86',
    'Karine',
    'f',
    '1947-11-07',
    'Polyarthrite rhumatoïde ',
    '2021-07-11',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '87',
    'Pauline',
    'f',
    '1994-02-07',
    'Maladies inflammatoires chroniques',
    '2022-01-24',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '88',
    'Stella',
    'f',
    '1975-12-06',
    'Myopathie ou myasthénie',
    '2021-11-25',
    '02'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '89',
    'Yasmina',
    'f',
    '1960-11-17',
    'Maladies rares',
    '2021-08-17',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '90',
    'Saoirse',
    'f',
    '2007-03-12',
    'Maladies inflammatoires chroniques',
    '2021-01-14',
    '59'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '91',
    'Marguerite',
    'f',
    '1978-02-26',
    'Cancer de la prostate',
    '2021-03-17',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '92',
    'Meryem',
    'f',
    '1979-12-10',
    'Troubles addictifs',
    '2022-03-06',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '93',
    'Audrey',
    'f',
    '1976-09-12',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-05-11',
    '26'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '94',
    'Hervé',
    'm',
    '1940-11-19',
    'Maladie de Parkinson',
    '2021-12-27',
    '02'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '95',
    'Brice',
    'm',
    '2001-08-25',
    'Cancer colorectal',
    '2022-12-02',
    '27'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '96',
    'Hamza',
    'm',
    '1941-02-15',
    'Polyarthrite rhumatoïde ',
    '2021-02-05',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '97',
    'Evelyn',
    'f',
    '1970-12-25',
    'Accident vasculaire cérébral',
    '2022-07-21',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '98',
    'Gabrielle',
    'f',
    '2005-07-24',
    'Troubles addictifs',
    '2022-06-13',
    '89'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '99',
    'Halima',
    'f',
    '1951-10-29',
    'Maladies rares',
    '2022-09-10',
    '79'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '100',
    'Josette',
    'f',
    '1936-07-16',
    'Maladie de Parkinson',
    '2022-08-13',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '101',
    'Didier',
    'm',
    '1957-04-16',
    'Cancer colorectal',
    '2023-07-27',
    '971'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '102',
    'Violet',
    'f',
    '1989-03-14',
    'Maladie valvulaire',
    '2023-02-06',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '103',
    'Simon',
    'm',
    '1937-10-06',
    'Cancer du sein de la femme',
    '2023-10-14',
    '94'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '104',
    'Jules',
    'm',
    '1992-07-20',
    'Accident vasculaire cérébral',
    '2021-07-29',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '105',
    'Mohamed',
    'm',
    '2011-03-26',
    'Diabète',
    '2021-08-15',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '106',
    'Soraya',
    'f',
    '2009-11-06',
    'Cancer bronchopulmonaire',
    '2021-04-18',
    '16'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '107',
    'Lorenzo',
    'm',
    '1997-04-26',
    'Diabète',
    '2022-02-15',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '108',
    'Sofiane',
    'm',
    '1989-01-31',
    'Troubles addictifs',
    '2021-01-24',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '109',
    'Stéphane',
    'm',
    '1964-11-10',
    'Cancer colorectal',
    '2023-02-17',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '110',
    'Yoann',
    'm',
    '1944-08-16',
    'Cancer bronchopulmonaire',
    '2023-02-19',
    '37'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '111',
    'Thierry',
    'm',
    '1978-07-04',
    'Diabète',
    '2023-08-15',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '112',
    'Laurent',
    'm',
    '1944-01-17',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-11-08',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '113',
    'Pierre',
    'm',
    '1968-02-05',
    'Troubles addictifs',
    '2023-03-08',
    '41'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '114',
    'Lucienne',
    'f',
    '1945-03-11',
    'Cancer colorectal',
    '2023-05-17',
    '09'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '115',
    'Karim',
    'm',
    '1973-06-03',
    'Maladie valvulaire',
    '2023-04-23',
    '55'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '116',
    'Luke',
    'm',
    '1977-03-23',
    'Mucoviscidose',
    '2023-08-26',
    '63'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '117',
    'Noémie',
    'f',
    '1997-08-11',
    'Cancer de la prostate',
    '2022-07-28',
    '63'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '118',
    'Iris',
    'f',
    '2014-11-27',
    'Cancer du sein de la femme',
    '2021-09-28',
    '15'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '119',
    'Anthony',
    'm',
    '2017-05-04',
    'Accident vasculaire cérébral',
    '2023-04-20',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '120',
    'Josiane',
    'f',
    '1957-11-07',
    'Cancer de la prostate',
    '2023-07-15',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '121',
    'Christian',
    'm',
    '1940-02-23',
    'Mucoviscidose',
    '2021-09-16',
    '87'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '122',
    'Juliette',
    'f',
    '1976-06-01',
    'Maladies rares',
    '2023-08-26',
    '08'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '123',
    'Alexandre',
    'm',
    '2016-12-26',
    'Polyarthrite rhumatoïde ',
    '2021-09-14',
    '15'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '124',
    'Elijah',
    'm',
    '1969-04-08',
    'Accident vasculaire cérébral',
    '2022-03-15',
    '22'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '125',
    'Logan',
    'm',
    '1996-03-03',
    'Polyarthrite rhumatoïde ',
    '2022-05-19',
    '67'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '126',
    'Léana',
    'f',
    '2003-10-04',
    'Diabète',
    '2023-12-05',
    '24'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '127',
    'Mélissa',
    'f',
    '1985-04-06',
    'Accident vasculaire cérébral',
    '2021-02-07',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '128',
    'Savannah',
    'f',
    '1999-09-14',
    'Diabète',
    '2021-03-25',
    '44'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '129',
    'Owen',
    'm',
    '1997-03-06',
    'Cancer colorectal',
    '2023-05-05',
    '75'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '130',
    'Nino',
    'm',
    '1997-08-05',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-07-09',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '131',
    'Ophélie',
    'f',
    '1986-02-25',
    'Myopathie ou myasthénie',
    '2023-06-08',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '132',
    'Paisley',
    'f',
    '2005-12-13',
    'Maladie de Parkinson',
    '2021-07-24',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '133',
    'Patricia',
    'f',
    '1968-11-19',
    'Embolie pulmonaire',
    '2021-01-20',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '134',
    'Zoé',
    'f',
    '2013-05-15',
    'Insuffisance cardiaque',
    '2022-05-03',
    '38'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '135',
    'Nathan',
    'm',
    '1991-12-23',
    'Troubles addictifs',
    '2022-01-23',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '136',
    'Alanna',
    'f',
    '1996-11-12',
    'Troubles psychotiques',
    '2022-09-05',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '137',
    'Noah',
    'm',
    '2000-12-05',
    'Myopathie ou myasthénie',
    '2021-01-19',
    '40'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '138',
    'Naima',
    'f',
    '2013-10-12',
    'Maladies rares',
    '2022-08-24',
    '66'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '139',
    'Ahmed',
    'm',
    '2015-11-15',
    'Cancer bronchopulmonaire',
    '2021-10-21',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '140',
    'Christophe',
    'm',
    '1939-07-03',
    'Insuffisance cardiaque',
    '2021-04-10',
    '49'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '141',
    'Cyril',
    'm',
    '2004-07-10',
    'Diabète',
    '2021-10-10',
    '90'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '142',
    'Guillaume',
    'm',
    '1955-10-21',
    'Mucoviscidose',
    '2023-03-23',
    '49'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '143',
    'Alice',
    'f',
    '2003-01-07',
    'Mucoviscidose',
    '2022-05-25',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '144',
    'Eleanor',
    'f',
    '1950-11-16',
    'Cancer de la prostate',
    '2021-03-01',
    '67'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '145',
    'Germaine',
    'f',
    '1929-08-11',
    'Cancer colorectal',
    '2021-05-03',
    '87'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '146',
    'Cillian',
    'm',
    '1935-03-29',
    'Cancer de la prostate',
    '2023-04-23',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '147',
    'Ellie',
    'm',
    '2014-11-08',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-04-07',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '148',
    'Gavin',
    'm',
    '1942-10-04',
    'Myopathie ou myasthénie',
    '2022-06-19',
    '69'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '149',
    'Frédéric',
    'm',
    '1954-02-10',
    'Cancer du sein de la femme',
    '2022-11-18',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '150',
    'Liam',
    'm',
    '2003-10-18',
    'Troubles psychotiques',
    '2023-06-11',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '151',
    'Gabriel',
    'm',
    '1955-11-15',
    'Maladies rares',
    '2021-01-16',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '152',
    'Léon',
    'm',
    '1970-10-15',
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-01-28',
    '63'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '153',
    'Malak',
    'm',
    '2006-08-15',
    'Troubles addictifs',
    '2022-05-15',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '154',
    'Bernard',
    'm',
    '1932-11-27',
    'Polyarthrite rhumatoïde ',
    '2021-11-03',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '155',
    'Andrée',
    'f',
    '1927-02-09',
    'Embolie pulmonaire',
    '2022-12-22',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '156',
    'Côme',
    'm',
    '1936-07-16',
    'Insuffisance cardiaque',
    '2022-05-23',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '157',
    'Dimitri',
    'm',
    '1946-07-17',
    'Cancer de la prostate',
    '2022-10-14',
    '16'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '158',
    'Ibtissam',
    'f',
    '1940-06-30',
    'Maladies rares',
    '2022-10-10',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '159',
    'Lydie',
    'f',
    '1964-06-15',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-08-09',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '160',
    'Michel',
    'm',
    '1941-08-03',
    'Maladie de Parkinson',
    '2021-08-21',
    '52'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '161',
    'Leïla',
    'f',
    '2015-04-02',
    'Maladies inflammatoires chroniques',
    '2022-06-19',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '162',
    'Samuel',
    'm',
    '1981-09-16',
    'Maladies inflammatoires chroniques',
    '2022-06-20',
    '19'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '163',
    'Mélanie',
    'f',
    '1983-03-14',
    'Polyarthrite rhumatoïde ',
    '2022-02-14',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '164',
    'Karima',
    'f',
    '2009-03-05',
    'Polyarthrite rhumatoïde ',
    '2021-12-14',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '165',
    'Sandrine',
    'f',
    '1952-08-12',
    'Myopathie ou myasthénie',
    '2023-10-13',
    '42'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '166',
    'Rachida',
    'f',
    '1957-06-11',
    'Diabète',
    '2021-10-06',
    '42'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '167',
    'Julian',
    'm',
    '2019-01-14',
    'Maladies rares',
    '2021-05-30',
    '65'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '168',
    'Léonie',
    'f',
    '1991-07-18',
    'Maladie valvulaire',
    '2022-05-29',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '169',
    'Régis',
    'm',
    '1949-04-14',
    'Diabète',
    '2021-10-18',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '170',
    'Vanessa',
    'f',
    '1970-08-04',
    'Cancer de la prostate',
    '2022-03-07',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '171',
    'Zahra',
    'f',
    '1977-09-07',
    'Cancer du sein de la femme',
    '2021-01-15',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '172',
    'Laetitia',
    'f',
    '1998-04-25',
    'Cancer du sein de la femme',
    '2022-06-11',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '173',
    'Julie',
    'f',
    '2005-10-28',
    'Cancer colorectal',
    '2021-10-20',
    '68'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '174',
    'Jérémy',
    'm',
    '1978-11-13',
    'Insuffisance cardiaque',
    '2023-02-05',
    '69'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '175',
    'Dounia',
    'f',
    '1931-12-17',
    'Troubles addictifs',
    '2022-11-15',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '176',
    'Charlotte',
    'f',
    '1951-09-10',
    'Maladies inflammatoires chroniques',
    '2021-03-25',
    '09'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '177',
    'Céline',
    'f',
    '1956-04-29',
    'Mucoviscidose',
    '2021-03-11',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '178',
    'Capucine',
    'f',
    '1957-08-27',
    'Cancer de la prostate',
    '2023-04-21',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '179',
    'Amandine',
    'f',
    '1979-03-24',
    'Troubles addictifs',
    '2021-02-17',
    '60'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '180',
    'Molly',
    'f',
    '2005-09-19',
    'Cancer bronchopulmonaire',
    '2021-10-05',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '181',
    'Martine',
    'f',
    '1946-02-05',
    'Cancer du sein de la femme',
    '2023-02-03',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '182',
    'Magali',
    'f',
    '1989-02-18',
    'Troubles psychotiques',
    '2023-06-10',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '183',
    'Nina',
    'f',
    '1991-04-26',
    'Maladies rares',
    '2022-06-23',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '184',
    'Hannah',
    'f',
    '1942-03-20',
    'Polyarthrite rhumatoïde ',
    '2023-02-10',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '185',
    'Nawal',
    'f',
    '1938-11-06',
    'Embolie pulmonaire',
    '2023-07-13',
    '91'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '186',
    'Philippine',
    'f',
    '1941-08-16',
    'Cancer de la prostate',
    '2021-04-25',
    '52'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '187',
    'Sophia',
    'f',
    '2018-05-04',
    'Maladies rares',
    '2022-10-01',
    '973'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '188',
    'Zineb',
    'f',
    '2002-11-19',
    'Cancer de la prostate',
    '2021-11-14',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '189',
    'Lucie',
    'f',
    '1937-06-06',
    'Maladie de Parkinson',
    '2022-06-11',
    '32'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '190',
    'Michèle',
    'f',
    '1948-03-22',
    'Accident vasculaire cérébral',
    '2021-10-25',
    '32'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '191',
    'Liv',
    'm',
    '2003-09-01',
    'Cancer colorectal',
    '2021-02-10',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '192',
    'Raphaël',
    'm',
    '2019-01-26',
    'Troubles addictifs',
    '2021-11-16',
    '94'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '193',
    'Théo',
    'm',
    '2009-03-21',
    'Maladie valvulaire',
    '2023-03-18',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '194',
    'Élodie',
    'f',
    '2000-05-22',
    'Cancer colorectal',
    '2023-10-11',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '195',
    'Chloé',
    'f',
    '1971-01-17',
    'Cancer bronchopulmonaire',
    '2021-07-20',
    '79'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '196',
    'Djamel',
    'm',
    '1998-10-03',
    'Embolie pulmonaire',
    '2022-06-19',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '197',
    'Aurore',
    'f',
    '1954-07-03',
    'Cancer de la prostate',
    '2021-07-09',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '198',
    'Camille',
    'f',
    '1927-10-16',
    'Embolie pulmonaire',
    '2023-06-28',
    '90'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '199',
    'Aoife',
    'f',
    '2004-05-12',
    'Maladie de Parkinson',
    '2022-05-22',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '200',
    'Charles',
    'm',
    '1982-06-24',
    'Maladie de Parkinson',
    '2022-01-03',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '201',
    'Damien',
    'm',
    '1940-03-16',
    'Troubles addictifs',
    '2021-10-02',
    '72'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '202',
    'Elias',
    'm',
    '2012-02-06',
    'Cancer du sein de la femme',
    '2021-01-17',
    '04'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '203',
    'Francis',
    'm',
    '1960-03-07',
    'Maladies rares',
    '2021-07-09',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '204',
    'Benjamin',
    'm',
    '1945-10-31',
    'Mucoviscidose',
    '2021-10-28',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '205',
    'Fabrice',
    'm',
    '1975-02-13',
    'Embolie pulmonaire',
    '2022-05-01',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '206',
    'Khaled',
    'm',
    '2006-04-21',
    'Insuffisance cardiaque',
    '2021-02-04',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '207',
    'Hugo',
    'm',
    '1988-09-14',
    'Cancer du sein de la femme',
    '2022-09-16',
    '60'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '208',
    'Florian',
    'm',
    '2007-11-20',
    'Cancer du sein de la femme',
    '2021-01-23',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '209',
    'Eliott',
    'm',
    '1971-02-01',
    'Maladie de Parkinson',
    '2022-11-14',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '210',
    'Hind',
    'f',
    '1997-10-15',
    'Embolie pulmonaire',
    '2023-06-24',
    '87'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '211',
    'Manon',
    'f',
    '2009-08-25',
    'Insuffisance cardiaque',
    '2022-11-14',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '212',
    'Justine',
    'f',
    '2012-07-28',
    'Embolie pulmonaire',
    '2021-06-25',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '213',
    'Jeremiah',
    'm',
    '1989-12-15',
    'Mucoviscidose',
    '2023-08-10',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '214',
    'Maya',
    'f',
    '1982-03-15',
    'Cancer bronchopulmonaire',
    '2021-08-25',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '215',
    'Ryan',
    'm',
    '2001-11-04',
    'Accident vasculaire cérébral',
    '2023-06-03',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '216',
    'Milo',
    'm',
    '1978-03-11',
    'Maladies rares',
    '2022-03-20',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '217',
    'Nadège',
    'f',
    '1965-05-14',
    'Cancer colorectal',
    '2022-12-14',
    '973'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '218',
    'Isabella',
    'f',
    '1961-08-04',
    'Cancer du sein de la femme',
    '2021-10-14',
    '33'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '219',
    'Fabien',
    'm',
    '1992-12-30',
    'Maladies inflammatoires chroniques',
    '2022-08-25',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '220',
    'Nisrine',
    'f',
    '1999-07-03',
    'Polyarthrite rhumatoïde ',
    '2021-03-27',
    '52'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '221',
    'Oisín',
    'f',
    '1958-03-09',
    'Myopathie ou myasthénie',
    '2021-09-24',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '222',
    'Pascal',
    'm',
    '1987-07-19',
    'Troubles psychotiques',
    '2022-10-14',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '223',
    'Tarek',
    'm',
    '1956-05-06',
    'Maladies inflammatoires chroniques',
    '2021-10-25',
    '42'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '224',
    'Nadia',
    'f',
    '1988-06-06',
    'Troubles psychotiques',
    '2021-07-19',
    '80'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '225',
    'Yanis',
    'm',
    '2013-06-18',
    'Cancer de la prostate',
    '2023-07-09',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '226',
    'Émilie',
    'f',
    '1940-09-11',
    'Diabète',
    '2021-01-09',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '227',
    'Jordan',
    'm',
    '2006-07-19',
    'Mucoviscidose',
    '2021-03-23',
    '48'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '228',
    'Caroline',
    'f',
    '1984-08-07',
    'Maladies rares',
    '2023-05-16',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '229',
    'Arnaud',
    'm',
    '1981-01-19',
    'Troubles psychotiques',
    '2022-03-01',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '230',
    'Isla',
    'f',
    '2016-07-30',
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-06-24',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '231',
    'Adel',
    'm',
    '1956-01-01',
    'Myopathie ou myasthénie',
    '2021-10-30',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '232',
    'Alban',
    'm',
    '1931-07-09',
    'Cancer colorectal',
    '2021-09-03',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '233',
    'Bruno',
    'm',
    '1990-08-12',
    'Cancer de la prostate',
    '2022-04-26',
    '69'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '234',
    'Ava',
    'f',
    '1988-02-17',
    'Accident vasculaire cérébral',
    '2021-06-19',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '235',
    'Gaëlle',
    'f',
    '1979-12-02',
    'Mucoviscidose',
    '2023-11-18',
    '95'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '236',
    'Jamila',
    'f',
    '2004-08-23',
    'Maladie valvulaire',
    '2022-08-13',
    '03'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '237',
    'Luc',
    'm',
    '1943-10-06',
    'Maladies inflammatoires chroniques',
    '2022-06-03',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '238',
    'Omar',
    'm',
    '1962-10-13',
    'Maladie de Parkinson',
    '2023-12-03',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '239',
    'Kawtar',
    'f',
    '1975-12-08',
    'Cancer du sein de la femme',
    '2021-08-28',
    '95'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '240',
    'Robin',
    'm',
    '1984-05-29',
    'Maladies inflammatoires chroniques',
    '2023-02-16',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '241',
    'Louise',
    'f',
    '1945-01-14',
    'Embolie pulmonaire',
    '2021-03-07',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '242',
    'Florence',
    'f',
    '1932-04-29',
    'Mucoviscidose',
    '2021-11-12',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '243',
    'Samira',
    'f',
    '1931-12-31',
    'Troubles addictifs',
    '2023-02-13',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '244',
    'Rose',
    'f',
    '1960-07-28',
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-04-13',
    '15'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '245',
    'Katie',
    'f',
    '1980-08-24',
    'Accident vasculaire cérébral',
    '2023-10-15',
    '52'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '246',
    'William',
    'm',
    '1975-04-16',
    'Cancer du sein de la femme',
    '2023-03-13',
    '91'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '247',
    'Manuel',
    'm',
    '1985-12-01',
    'Polyarthrite rhumatoïde ',
    '2021-06-03',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '248',
    'Tao',
    'm',
    '1950-09-09',
    'Cancer colorectal',
    '2022-04-04',
    '59'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '249',
    'Salim',
    'm',
    '1959-09-26',
    'Cancer colorectal',
    '2022-04-06',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '250',
    'Malo',
    'm',
    '2007-02-04',
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-08-20',
    '80'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '251',
    'Dominique',
    'm',
    '1953-09-16',
    'Maladies rares',
    '2022-06-02',
    '35'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '252',
    'Jean-Philippe',
    'm',
    '1956-12-11',
    'Myopathie ou myasthénie',
    '2022-05-25',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '253',
    'Kenza',
    'f',
    '1974-11-21',
    'Myopathie ou myasthénie',
    '2021-12-27',
    '75'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '254',
    'Jana',
    'm',
    '2018-05-30',
    'Cancer colorectal',
    '2023-12-11',
    '19'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '255',
    'Lamia',
    'f',
    '1971-04-04',
    'Maladies inflammatoires chroniques',
    '2023-04-08',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '256',
    'Eden',
    'm',
    '1972-05-19',
    'Mucoviscidose',
    '2023-08-18',
    '89'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '257',
    'Noé',
    'm',
    '1929-05-17',
    'Maladie de Parkinson',
    '2022-07-09',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '258',
    'Lise',
    'f',
    '1982-01-19',
    'Insuffisance cardiaque',
    '2022-10-07',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '259',
    'Sabrina',
    'f',
    '2007-06-19',
    'Cancer de la prostate',
    '2022-06-28',
    '69'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '260',
    'Nathalie',
    'f',
    '1957-10-21',
    'Mucoviscidose',
    '2023-04-25',
    '30'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '261',
    'Akim',
    'm',
    '1932-11-12',
    'Maladie valvulaire',
    '2022-07-31',
    '46'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '262',
    'Grace',
    'f',
    '1942-07-24',
    'Maladies inflammatoires chroniques',
    '2022-10-30',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '263',
    'Josiah',
    'm',
    '1988-06-05',
    'Embolie pulmonaire',
    '2021-09-08',
    '85'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '264',
    'Quentin',
    'm',
    '2017-01-20',
    'Cancer bronchopulmonaire',
    '2023-04-02',
    '19'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '265',
    'Jake',
    'm',
    '2013-12-22',
    'Maladies inflammatoires chroniques',
    '2021-04-21',
    '38'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '266',
    'Rachid',
    'm',
    '1943-12-19',
    'Myopathie ou myasthénie',
    '2022-06-04',
    '87'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '267',
    'Gianna',
    'f',
    '1958-04-07',
    'Maladie valvulaire',
    '2022-11-29',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '268',
    'Harry',
    'm',
    '1991-01-27',
    'Maladies inflammatoires chroniques',
    '2021-02-05',
    '19'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '269',
    'Hazel',
    'f',
    '1988-09-08',
    'Troubles addictifs',
    '2023-05-05',
    '64'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '270',
    'Michael',
    'm',
    '1937-03-14',
    'Cancer du sein de la femme',
    '2021-12-16',
    '10'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '271',
    'Hudson',
    'f',
    '1948-03-04',
    'Cancer du sein de la femme',
    '2022-04-23',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '272',
    'Imane',
    'f',
    '1984-10-20',
    'Troubles psychotiques',
    '2022-11-23',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '273',
    'Eli',
    'm',
    '1950-11-10',
    'Diabète',
    '2022-07-19',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '274',
    'Julia',
    'f',
    '1941-10-22',
    'Maladies inflammatoires chroniques',
    '2022-04-26',
    '12'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '275',
    'Alain',
    'm',
    '1990-04-21',
    'Maladie de Parkinson',
    '2023-08-03',
    '81'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '276',
    'Claire',
    'f',
    '1946-05-30',
    'Maladie de Parkinson',
    '2021-05-03',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '277',
    'Arthur',
    'm',
    '2002-02-23',
    'Cancer colorectal',
    '2021-07-12',
    '16'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '278',
    'Elise',
    'f',
    '2010-07-22',
    'Cancer de la prostate',
    '2022-07-21',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '279',
    'Delphine',
    'f',
    '1971-08-03',
    'Embolie pulmonaire',
    '2022-10-22',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '280',
    'alanna',
    'f',
    '1993-02-13',
    'Diabète',
    '2022-01-23',
    '44'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '281',
    'Maëlys',
    'f',
    '1944-08-22',
    'Troubles psychotiques',
    '2022-07-23',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '282',
    'Hanae',
    'f',
    '1940-09-16',
    'Mucoviscidose',
    '2021-06-20',
    '41'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '283',
    'Marc',
    'm',
    '1965-01-27',
    'Embolie pulmonaire',
    '2021-07-17',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '284',
    'Isaiah',
    'm',
    '1982-08-06',
    'Mucoviscidose',
    '2022-11-30',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '285',
    'Cédric',
    'm',
    '1962-03-11',
    'Polyarthrite rhumatoïde ',
    '2023-11-18',
    '63'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '286',
    'Imran',
    'm',
    '1930-06-03',
    'Maladies rares',
    '2022-10-29',
    '10'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '287',
    'Daniel',
    'm',
    '1926-06-10',
    'Maladies inflammatoires chroniques',
    '2023-09-17',
    '68'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '288',
    'Chantal',
    'f',
    '1929-04-02',
    'Troubles addictifs',
    '2023-12-24',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '289',
    'Léa',
    'f',
    '1938-03-21',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-23',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '290',
    'Inès',
    'f',
    '2014-07-06',
    'Troubles psychotiques',
    '2022-07-24',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '291',
    'Marius',
    'm',
    '1967-11-18',
    'Insuffisance cardiaque',
    '2022-07-22',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '292',
    'Hunter',
    'm',
    '1976-11-24',
    'Maladie de Parkinson',
    '2022-02-20',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '293',
    'Harper',
    'm',
    '1999-01-20',
    'Troubles addictifs',
    '2023-09-27',
    '30'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '294',
    'Emilia',
    'f',
    '1950-10-22',
    'Polyarthrite rhumatoïde ',
    '2021-01-09',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '295',
    'Ella',
    'f',
    '1996-03-19',
    'Cancer du sein de la femme',
    '2023-04-07',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '296',
    'Clarisse',
    'f',
    '1955-09-04',
    'Embolie pulmonaire',
    '2022-05-12',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '297',
    'Kai',
    'm',
    '1983-07-19',
    'Troubles addictifs',
    '2022-01-09',
    '56'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '298',
    'Jeannine',
    'f',
    '1935-06-03',
    'Insuffisance cardiaque',
    '2021-10-15',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '299',
    'Romain',
    'm',
    '2003-01-03',
    'Accident vasculaire cérébral',
    '2023-06-08',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '300',
    'Riley',
    'm',
    '1963-10-12',
    'Embolie pulmonaire',
    '2023-05-23',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '301',
    'Souad',
    'm',
    '1948-08-22',
    'Cancer du sein de la femme',
    '2023-03-17',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '302',
    'Samantha',
    'f',
    '1949-08-01',
    'Cancer colorectal',
    '2023-02-13',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '303',
    'Tatiana',
    'f',
    '1957-09-10',
    'Maladies rares',
    '2021-09-03',
    '24'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '304',
    'Valentin',
    'm',
    '2011-03-29',
    'Cancer de la prostate',
    '2021-04-09',
    '80'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '305',
    'Zakaria',
    'm',
    '1933-09-21',
    'Maladie de Parkinson',
    '2023-11-30',
    '37'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '306',
    'Sylvain',
    'm',
    '1968-02-18',
    'Myopathie ou myasthénie',
    '2022-04-04',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '307',
    'Fatim',
    'm',
    '2002-02-08',
    'Maladies inflammatoires chroniques',
    '2023-10-30',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '308',
    'Emmanuelle',
    'f',
    '1928-07-14',
    'Myopathie ou myasthénie',
    '2021-03-29',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '309',
    'Aïcha',
    'f',
    '1997-07-28',
    'Cancer du sein de la femme',
    '2022-09-12',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '310',
    'Bilal',
    'm',
    '2009-11-10',
    'Maladies inflammatoires chroniques',
    '2022-02-25',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '311',
    'Caleb',
    'm',
    '2007-11-24',
    'Cancer de la prostate',
    '2021-09-12',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '312',
    'Adrian',
    'm',
    '1972-02-12',
    'Maladies rares',
    '2023-03-07',
    '971'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '313',
    'Layla',
    'f',
    '2001-06-29',
    'Troubles psychotiques',
    '2023-04-05',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '314',
    'Madeleine',
    'f',
    '1994-12-23',
    'Accident vasculaire cérébral',
    '2023-05-25',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '315',
    'Olivia',
    'f',
    '1981-09-23',
    'Cancer de la prostate',
    '2022-08-04',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '316',
    'Rafael',
    'm',
    '1983-09-26',
    'Maladie de Parkinson',
    '2023-05-21',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '317',
    'Timéo',
    'm',
    '2008-03-24',
    'Accident vasculaire cérébral',
    '2021-08-01',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '318',
    'Léo',
    'm',
    '1941-02-07',
    'Cancer du sein de la femme',
    '2022-08-24',
    '31'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '319',
    'Nicolas',
    'm',
    '1932-07-28',
    'Embolie pulmonaire',
    '2023-01-05',
    '33'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '320',
    'Sami',
    'm',
    '1925-06-23',
    'Troubles psychotiques',
    '2021-05-29',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '321',
    'Noura',
    'f',
    '1966-05-04',
    'Maladies inflammatoires chroniques',
    '2023-08-19',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '322',
    'Mia',
    'f',
    '1997-07-29',
    'Maladie valvulaire',
    '2022-09-25',
    '89'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '323',
    'Ludo',
    'm',
    '1957-10-30',
    'Maladie valvulaire',
    '2023-03-29',
    '46'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '324',
    'Robert',
    'm',
    '1997-10-23',
    'Mucoviscidose',
    '2023-01-07',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '325',
    'Soren',
    'm',
    '1983-04-13',
    'Accident vasculaire cérébral',
    '2023-03-30',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '326',
    'Yann',
    'm',
    '1963-07-27',
    'Maladie valvulaire',
    '2022-09-10',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '327',
    'Jacqueline',
    'f',
    '1982-06-26',
    'Cancer du sein de la femme',
    '2022-02-13',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '328',
    'Lina',
    'f',
    '1989-03-24',
    'Cancer bronchopulmonaire',
    '2021-10-23',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '329',
    'James',
    'm',
    '2019-11-04',
    'Embolie pulmonaire',
    '2023-12-05',
    '16'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '330',
    'Penelope',
    'f',
    '1939-10-23',
    'Embolie pulmonaire',
    '2023-09-01',
    '30'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '331',
    'Amelia',
    'f',
    '1989-11-24',
    'Diabète',
    '2022-09-07',
    '81'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '332',
    'Dalia',
    'f',
    '1970-10-28',
    'Myopathie ou myasthénie',
    '2023-08-02',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '333',
    'Victor',
    'm',
    '1966-05-17',
    'Maladies rares',
    '2023-04-24',
    '68'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '334',
    'Ambre',
    'f',
    '1934-10-21',
    'Cancer bronchopulmonaire',
    '2021-09-06',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '335',
    'Fares',
    'm',
    '1934-07-28',
    'Cancer colorectal',
    '2021-04-01',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '336',
    'Emma',
    'f',
    '1935-02-27',
    'Polyarthrite rhumatoïde ',
    '2023-04-07',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '337',
    'Alicia',
    'f',
    '1937-10-10',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-02-23',
    '38'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '338',
    'Christine',
    'f',
    '1998-02-11',
    'Troubles addictifs',
    '2023-05-11',
    '62'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '339',
    'Axel',
    'm',
    '1956-03-09',
    'Troubles addictifs',
    '2023-08-21',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '340',
    'Amal',
    'f',
    '1934-03-18',
    'Maladies inflammatoires chroniques',
    '2021-05-07',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '341',
    'Ezra',
    'm',
    '1958-12-16',
    'Cancer colorectal',
    '2021-04-28',
    '43'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '342',
    'Colton',
    'm',
    '2004-01-22',
    'Troubles addictifs',
    '2022-12-25',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '343',
    'Bénédicte',
    'f',
    '1991-12-06',
    'Cancer du sein de la femme',
    '2022-09-16',
    '04'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '344',
    'Ali',
    'm',
    '1969-07-16',
    'Maladie valvulaire',
    '2021-07-27',
    '79'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '345',
    'Freya',
    'f',
    '2018-01-28',
    'Cancer du sein de la femme',
    '2021-06-30',
    '01'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '346',
    'Clara',
    'f',
    '2017-03-15',
    'Polyarthrite rhumatoïde ',
    '2022-07-07',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '347',
    'Chloe',
    'f',
    '1979-09-12',
    'Polyarthrite rhumatoïde ',
    '2022-01-28',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '348',
    'Sacha',
    'f',
    '1941-12-13',
    'Accident vasculaire cérébral',
    '2022-05-26',
    '971'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '349',
    'Nolan',
    'm',
    '1999-01-01',
    'Maladies rares',
    '2023-06-19',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '350',
    'Reda',
    'm',
    '1991-05-06',
    'Polyarthrite rhumatoïde ',
    '2022-08-24',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '351',
    'Samir',
    'm',
    '1963-10-25',
    'Embolie pulmonaire',
    '2021-07-30',
    '59'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '352',
    'Thibault',
    'm',
    '2018-06-14',
    'Mucoviscidose',
    '2021-03-16',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '353',
    'Lily',
    'f',
    '1971-08-04',
    'Polyarthrite rhumatoïde ',
    '2023-03-10',
    '13'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '354',
    'Thomas',
    'f',
    '2013-08-01',
    'Maladie de Parkinson',
    '2021-12-10',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '355',
    'Nordin',
    'm',
    '2005-05-13',
    'Insuffisance cardiaque',
    '2023-01-17',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '356',
    'Tony',
    'f',
    '1956-08-20',
    'Diabète',
    '2023-03-14',
    '41'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '357',
    'Jack',
    'm',
    '1952-05-17',
    'Troubles psychotiques',
    '2022-03-31',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '358',
    'Elsa',
    'f',
    '1984-07-07',
    'Polyarthrite rhumatoïde ',
    '2022-01-19',
    '81'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '359',
    'Jihad',
    'm',
    '2017-11-12',
    'Maladies inflammatoires chroniques',
    '2023-05-10',
    '91'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '360',
    'Brayden',
    'm',
    '1989-10-16',
    'Mucoviscidose',
    '2021-07-21',
    '45'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '361',
    'Aurélie',
    'f',
    '1936-01-28',
    'Maladie de Parkinson',
    '2021-11-30',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '362',
    'Kennedy',
    'm',
    '1950-09-15',
    'Embolie pulmonaire',
    '2022-03-28',
    '48'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '363',
    'Luna',
    'f',
    '2015-07-08',
    'Troubles psychotiques',
    '2021-05-23',
    '07'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '364',
    'Iman',
    'm',
    '1953-09-14',
    'Embolie pulmonaire',
    '2021-01-16',
    '25'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '365',
    'Luka',
    'm',
    '1981-12-03',
    'Polyarthrite rhumatoïde ',
    '2021-07-21',
    '94'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '366',
    'Alexander',
    'm',
    '1971-02-13',
    'Polyarthrite rhumatoïde ',
    '2022-02-24',
    '56'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '367',
    'Manal',
    'f',
    '1932-10-23',
    'Cancer colorectal',
    '2022-08-24',
    '78'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '368',
    'Mael',
    'm',
    '1938-01-13',
    'Mucoviscidose',
    '2021-04-26',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '369',
    'Nora',
    'f',
    '1984-04-05',
    'Mucoviscidose',
    '2021-05-03',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '370',
    'Maxime',
    'm',
    '2014-08-25',
    'Maladie de Parkinson',
    '2022-02-06',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '371',
    'Mathis',
    'm',
    '2013-04-28',
    'Maladies rares',
    '2022-12-14',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '372',
    'Yoan',
    'm',
    '1958-09-18',
    'Accident vasculaire cérébral',
    '2021-12-09',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '373',
    'Yannick',
    'm',
    '1961-05-08',
    'Troubles psychotiques',
    '2021-10-05',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '374',
    'Lucy',
    'f',
    '1949-08-18',
    'Troubles addictifs',
    '2022-02-04',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '375',
    'Nadine',
    'f',
    '2008-07-01',
    'Troubles addictifs',
    '2021-04-19',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '376',
    'Léane',
    'f',
    '2002-03-04',
    'Cancer du sein de la femme',
    '2022-12-10',
    '976'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '377',
    'Romy',
    'f',
    '1990-03-28',
    'Insuffisance cardiaque',
    '2022-10-01',
    '53'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '378',
    'Zara',
    'f',
    '1986-01-26',
    'Cancer colorectal',
    '2022-07-05',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '379',
    'Amina',
    'f',
    '1934-09-14',
    'Accident vasculaire cérébral',
    '2023-12-16',
    '26'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '380',
    'Fiadh',
    'm',
    '2012-05-24',
    'Cancer du sein de la femme',
    '2023-05-20',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '381',
    'Bella',
    'f',
    '1993-07-09',
    'Cancer bronchopulmonaire',
    '2023-02-28',
    '32'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '382',
    'Béatrice',
    'f',
    '1943-05-02',
    'Polyarthrite rhumatoïde ',
    '2022-12-18',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '383',
    'Corinne',
    'f',
    '1953-08-07',
    'Cancer bronchopulmonaire',
    '2023-09-20',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '384',
    'Lila',
    'f',
    '1933-04-01',
    'Maladies rares',
    '2022-10-01',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '385',
    'Mila',
    'f',
    '1965-04-18',
    'Polyarthrite rhumatoïde ',
    '2021-04-16',
    '2A'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '386',
    'Salma',
    'f',
    '1981-07-24',
    'Accident vasculaire cérébral',
    '2021-12-12',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '387',
    'Nabila',
    'f',
    '1951-07-12',
    'Polyarthrite rhumatoïde ',
    '2022-09-04',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '388',
    'Sandra',
    'f',
    '1989-03-06',
    'Maladie valvulaire',
    '2022-03-23',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '389',
    'Thérèse',
    'f',
    '1960-06-10',
    'Cancer du sein de la femme',
    '2021-09-16',
    '26'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '390',
    'Éric',
    'm',
    '1947-05-14',
    'Insuffisance cardiaque',
    '2023-01-06',
    '23'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '391',
    'Wissam',
    'm',
    '1985-02-02',
    'Cancer du sein de la femme',
    '2022-02-09',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '392',
    'Lena',
    'f',
    '1977-07-17',
    'Embolie pulmonaire',
    '2021-05-05',
    '49'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '393',
    'Sébastien',
    'm',
    '1954-12-06',
    'Cancer du sein de la femme',
    '2022-03-01',
    '45'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '394',
    'Abigail',
    'f',
    '1963-08-26',
    'Myopathie ou myasthénie',
    '2023-05-27',
    '973'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '395',
    'Agathe',
    'f',
    '1998-05-12',
    'Maladies inflammatoires chroniques',
    '2021-04-17',
    '92'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '396',
    'Brigitte',
    'f',
    '1982-11-17',
    'Myopathie ou myasthénie',
    '2023-11-02',
    '81'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '397',
    'Basil',
    'm',
    '1991-03-01',
    'Maladie valvulaire',
    '2022-01-06',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '398',
    'Mathilde',
    'f',
    '1999-07-07',
    'Embolie pulmonaire',
    '2021-06-12',
    '63'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '399',
    'Aya',
    'f',
    '1983-04-26',
    'Troubles addictifs',
    '2022-03-09',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '400',
    'Annie',
    'f',
    '1960-05-24',
    'Accident vasculaire cérébral',
    '2022-08-08',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '401',
    'Cameron',
    'm',
    '1975-11-18',
    'Diabète',
    '2023-11-26',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '402',
    'Emily',
    'f',
    '1973-01-09',
    'Maladies inflammatoires chroniques',
    '2021-07-31',
    '80'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '403',
    'allison',
    'f',
    '1927-02-11',
    'Maladies inflammatoires chroniques',
    '2021-08-08',
    '09'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '404',
    'Rayane',
    'm',
    '1954-03-07',
    'Troubles psychotiques',
    '2023-01-21',
    '09'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '405',
    'Sara',
    'f',
    '2019-07-27',
    'Maladies rares',
    '2021-10-19',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '406',
    'Zoey',
    'f',
    '1947-03-18',
    'Maladies inflammatoires chroniques',
    '2021-07-28',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '407',
    'Évelyne',
    'm',
    '1968-01-16',
    'Cancer bronchopulmonaire',
    '2023-03-10',
    '33'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '408',
    'Sofia',
    'f',
    '1955-02-18',
    'Troubles psychotiques',
    '2023-10-26',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '409',
    'Samia',
    'f',
    '2004-11-13',
    'Cancer bronchopulmonaire',
    '2022-02-14',
    '88'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '410',
    'Marie',
    'f',
    '1959-07-08',
    'Accident vasculaire cérébral',
    '2022-09-21',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '411',
    'Suzanne',
    'f',
    '1951-04-23',
    'Diabète',
    '2022-12-14',
    '54'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '412',
    'Yasmine',
    'f',
    '1948-03-31',
    'Myopathie ou myasthénie',
    '2023-06-26',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '413',
    'Valérie',
    'f',
    '1980-06-30',
    'Cancer colorectal',
    '2021-08-19',
    '92'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '414',
    'Mateo',
    'm',
    '1958-09-20',
    'Cancer colorectal',
    '2022-04-01',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '415',
    'Sophie',
    'f',
    '2015-04-11',
    'Cancer de la prostate',
    '2022-07-27',
    '82'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '416',
    'Louis',
    'm',
    '1930-04-29',
    'Accident vasculaire cérébral',
    '2023-04-03',
    '46'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '417',
    'Amine',
    'm',
    '1995-04-13',
    'Cancer bronchopulmonaire',
    '2021-10-11',
    '61'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '418',
    'Jean-Paul',
    'm',
    '1983-06-26',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-06-18',
    '72'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '419',
    'Fanny',
    'f',
    '1955-08-14',
    'Diabète',
    '2022-07-05',
    '52'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '420',
    'Gael',
    'm',
    '2017-06-13',
    'Maladie de Parkinson',
    '2022-10-21',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '421',
    'Grégory',
    'm',
    '1928-11-13',
    'Polyarthrite rhumatoïde ',
    '2023-07-19',
    '971'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '422',
    'Grégoire',
    'm',
    '2018-05-21',
    'Maladie de Parkinson',
    '2022-08-13',
    '2B'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '423',
    'Jean-François',
    'm',
    '2013-01-30',
    'Maladies rares',
    '2023-02-12',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '424',
    'Conor',
    'm',
    '1977-03-26',
    'Troubles addictifs',
    '2021-02-17',
    '77'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '425',
    'Anas',
    'm',
    '1978-09-23',
    'Cancer colorectal',
    '2022-04-10',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '426',
    'André',
    'm',
    '2006-08-14',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-10-06',
    '35'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '427',
    'Jackson',
    'm',
    '1981-04-24',
    'Troubles psychotiques',
    '2023-07-03',
    '47'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '428',
    'Anna',
    'f',
    '1935-11-21',
    'Mucoviscidose',
    '2023-02-28',
    '38'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '429',
    'Lino',
    'm',
    '2006-11-16',
    'Maladies inflammatoires chroniques',
    '2022-04-17',
    '15'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '430',
    'Luan',
    'm',
    '2017-04-28',
    'Cancer colorectal',
    '2022-03-22',
    '09'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '431',
    'Mickaël',
    'm',
    '1950-01-18',
    'Mucoviscidose',
    '2022-04-13',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '432',
    'Oliver',
    'm',
    '2015-01-09',
    'Maladie valvulaire',
    '2023-06-26',
    '44'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '433',
    'Sylviane',
    'f',
    '1925-01-17',
    'Cancer bronchopulmonaire',
    '2022-11-25',
    '35'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '434',
    'Yohan',
    'm',
    '2007-11-28',
    'Cancer bronchopulmonaire',
    '2021-06-30',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '435',
    'Yvonne',
    'f',
    '1935-10-07',
    'Insuffisance cardiaque',
    '2021-02-06',
    '21'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '436',
    'Lysander',
    'm',
    '1931-02-27',
    'Cancer colorectal',
    '2022-09-02',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '437',
    'Simone',
    'f',
    '1949-12-04',
    'Myopathie ou myasthénie',
    '2021-09-18',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '438',
    'Luca',
    'm',
    '1927-04-01',
    'Maladie de Parkinson',
    '2021-07-30',
    '18'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '439',
    'Aurora',
    'f',
    '1940-07-13',
    'Insuffisance cardiaque',
    '2022-10-02',
    '30'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '440',
    'Joffrey',
    'm',
    '1977-01-28',
    'Maladie valvulaire',
    '2023-09-20',
    '83'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '441',
    'Sebastian',
    'm',
    '1973-01-20',
    'Troubles psychotiques',
    '2021-04-13',
    '70'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '442',
    'Vincent',
    'm',
    '1958-09-26',
    'Myopathie ou myasthénie',
    '2022-05-09',
    '72'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '443',
    'Maceo',
    'm',
    '1937-10-29',
    'Cancer bronchopulmonaire',
    '2021-07-16',
    '65'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '444',
    'Landon',
    'm',
    '1934-03-08',
    'Cancer de la prostate',
    '2023-09-16',
    '19'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '445',
    'Virginie',
    'f',
    '1987-07-19',
    'Cancer du sein de la femme',
    '2023-05-09',
    '04'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '446',
    'Élisabeth',
    'f',
    '1927-05-20',
    'Mucoviscidose',
    '2021-06-07',
    '40'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '447',
    'Kinsley',
    'm',
    '1943-05-01',
    'Cancer du sein de la femme',
    '2023-11-27',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '448',
    'Séverine',
    'f',
    '1955-05-23',
    'Cancer colorectal',
    '2023-06-23',
    '46'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '449',
    'Youssef',
    'm',
    '1980-10-14',
    'Cancer du sein de la femme',
    '2021-12-15',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '450',
    'Lola',
    'f',
    '1962-05-16',
    'Troubles addictifs',
    '2022-01-09',
    '16'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '451',
    'Mohan',
    'm',
    '2012-07-29',
    'Cancer bronchopulmonaire',
    '2021-11-30',
    '43'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '452',
    'Lya',
    'f',
    '1985-06-06',
    'Embolie pulmonaire',
    '2021-03-24',
    '40'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '453',
    'Zoe',
    'f',
    '1943-10-10',
    'Troubles addictifs',
    '2022-04-20',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '454',
    'Sylvie',
    'f',
    '1955-04-08',
    'Diabète',
    '2022-04-23',
    '79'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '455',
    'Elizabeth',
    'f',
    '1976-03-05',
    'Maladies inflammatoires chroniques',
    '2023-09-23',
    '28'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '456',
    'Swann',
    'f',
    '2007-05-12',
    'Cancer du sein de la femme',
    '2021-12-26',
    '972'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '457',
    'Carole',
    'f',
    '1993-01-26',
    'Diabète',
    '2021-11-12',
    '06'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '458',
    'Anne',
    'f',
    '1985-03-04',
    'Maladie de Parkinson',
    '2021-05-12',
    '91'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '459',
    'Marcelle',
    'f',
    '1944-12-20',
    'Maladies inflammatoires chroniques',
    '2022-03-10',
    '35'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '460',
    'Skylar',
    'm',
    '1976-12-12',
    'Cancer de la prostate',
    '2023-07-17',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '461',
    'Leah',
    'f',
    '1956-05-13',
    'Troubles psychotiques',
    '2023-02-12',
    '65'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '462',
    'Monique',
    'f',
    '1996-01-17',
    'Embolie pulmonaire',
    '2021-09-10',
    '64'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '463',
    'Monica',
    'f',
    '1981-04-16',
    'Troubles psychotiques',
    '2021-09-17',
    '71'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '464',
    'Aubrey',
    'f',
    '1972-02-19',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-07-01',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '465',
    'Agnès',
    'f',
    '1958-09-14',
    'Embolie pulmonaire',
    '2023-04-17',
    '89'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '466',
    'Mason',
    'm',
    '1937-02-02',
    'Polyarthrite rhumatoïde ',
    '2022-03-06',
    '85'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '467',
    'Émilien',
    'm',
    '1975-07-14',
    'Maladie de Parkinson',
    '2022-01-01',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '468',
    'Danielle',
    'f',
    '1962-09-24',
    'Troubles addictifs',
    '2021-10-27',
    '971'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '469',
    'Greyson',
    'm',
    '1926-10-07',
    'Polyarthrite rhumatoïde ',
    '2022-05-05',
    '11'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '470',
    'Marion',
    'f',
    '1953-08-03',
    'Accident vasculaire cérébral',
    '2022-03-31',
    '50'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '471',
    'Theodore',
    'm',
    '1993-07-10',
    'Cancer de la prostate',
    '2023-07-21',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '472',
    'Odette',
    'f',
    '2001-01-24',
    'Myopathie ou myasthénie',
    '2022-07-21',
    '14'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '473',
    'Françoise',
    'f',
    '1982-10-08',
    'Embolie pulmonaire',
    '2021-01-29',
    '39'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '474',
    'Natalie',
    'f',
    '1979-11-10',
    'Insuffisance cardiaque',
    '2021-04-12',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '475',
    'Asher',
    'm',
    '1925-01-09',
    'Embolie pulmonaire',
    '2021-02-15',
    '84'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '476',
    'Gilberte',
    'f',
    '1985-10-13',
    'Cancer de la prostate',
    '2022-02-02',
    '65'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '477',
    'Eva',
    'f',
    '1992-11-26',
    'Myopathie ou myasthénie',
    '2023-10-08',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '478',
    'Amandine',
    'f',
    '2012-07-16',
    'Polyarthrite rhumatoïde ',
    '2023-06-28',
    '70'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '479',
    'Étienne',
    'm',
    '1932-08-03',
    'Insuffisance cardiaque',
    '2023-11-29',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '480',
    'Yassine',
    'f',
    '1993-07-24',
    'Troubles addictifs',
    '2023-01-06',
    '48'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '481',
    'Jean-Pierre',
    'm',
    '1989-03-25',
    'Embolie pulmonaire',
    '2023-03-10',
    '02'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '482',
    'Raymonde',
    'f',
    '1972-01-01',
    'Maladies rares',
    '2022-09-20',
    '86'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '483',
    'Janine',
    'f',
    '2005-07-24',
    'Polyarthrite rhumatoïde ',
    '2023-05-03',
    '34'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '484',
    'Luce',
    'f',
    '2019-12-02',
    'Maladies inflammatoires chroniques',
    '2021-09-20',
    '57'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '485',
    'Aiden',
    'm',
    '1931-12-17',
    'Maladies rares',
    '2021-02-28',
    '81'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '486',
    'Jean',
    'm',
    '1976-12-31',
    'Mucoviscidose',
    '2022-02-11',
    '93'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '487',
    'Rajaa',
    'f',
    '1968-09-09',
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-05-08',
    '29'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '488',
    'Wafa',
    'f',
    '1935-06-04',
    'Cancer du sein de la femme',
    '2022-08-27',
    '74'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '489',
    'John',
    'm',
    '1988-06-24',
    'Maladie de Parkinson',
    '2022-03-07',
    '974'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '490',
    'Mario',
    'm',
    '1967-10-17',
    'Accident vasculaire cérébral',
    '2022-11-30',
    '972'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '491',
    'Gabriella',
    'f',
    '1939-12-17',
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-08-06',
    '51'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '492',
    'Gina',
    'f',
    '1978-08-15',
    'Cancer du sein de la femme',
    '2023-03-14',
    '05'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '493',
    'Ursula',
    'f',
    '1984-01-07',
    'Embolie pulmonaire',
    '2022-06-04',
    '32'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '494',
    'Vita',
    'f',
    '1976-12-16',
    'Accident vasculaire cérébral',
    '2021-10-26',
    '69'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '495',
    'Genesis',
    'm',
    '1927-11-12',
    'Mucoviscidose',
    '2023-03-17',
    '17'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '496',
    'Ayoub',
    'm',
    '2003-03-27',
    'Maladie de Parkinson',
    '2022-06-03',
    '973'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '497',
    'Aaron',
    'm',
    '1991-01-27',
    'Cancer du sein de la femme',
    '2021-02-26',
    '55'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '498',
    'Fernandino',
    'm',
    '2019-08-26',
    'Cancer colorectal',
    '2023-06-05',
    '73'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '499',
    'Josefina',
    'f',
    '1941-10-27',
    'Mucoviscidose',
    '2022-11-18',
    '58'
);

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '500',
    'Leonora',
    'f',
    '2007-04-19',
    'Maladie de Parkinson',
    '2023-10-04',
    '973'
);
