
INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '1', 
    'aaliyah', 
    'f', 
    '1946-08-27', 
    'Troubles addictifs',
    '2021-01-12',
    '72'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '2', 
    'aapeli', 
    'm', 
    '1962-11-12', 
    'Cancer bronchopulmonaire',
    '2021-02-03',
    '75'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '3', 
    'aapo', 
    'm', 
    '1930-08-13', 
    'Mucoviscidose',
    '2022-03-12',
    '15'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '4', 
    'aaren', 
    'm', 
    '1985-04-08', 
    'Maladies inflammatoires chroniques',
    '2022-10-21',
    '64'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '5', 
    'aarne', 
    'm', 
    '1993-05-16', 
    'Maladies inflammatoires chroniques',
    '2022-07-04',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '6', 
    'aarón', 
    'm', 
    '1997-07-21', 
    'Cancer colorectal',
    '2023-02-26',
    '65'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '7', 
    'aaron', 
    'm', 
    '1931-10-08', 
    'Cancer du sein de la femme',
    '2023-08-23',
    '27'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '8', 
    'aatami', 
    'm', 
    '2001-08-12', 
    'Maladie de Parkinson',
    '2022-03-26',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '9', 
    'aatto', 
    'm', 
    '1967-06-16', 
    'Troubles psychotiques',
    '2023-02-01',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '10', 
    'aatu', 
    'm', 
    '2000-12-30', 
    'Polyarthrite rhumatoïde ',
    '2021-11-02',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '11', 
    'abaddon', 
    'm', 
    '1974-04-29', 
    'Cancer bronchopulmonaire',
    '2021-03-29',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '12', 
    'abbán', 
    'm', 
    '1979-11-14', 
    'Cancer de la prostate',
    '2023-06-30',
    '87'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '13', 
    'abbas', 
    'm', 
    '1934-11-21', 
    'Cancer bronchopulmonaire',
    '2023-04-26',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '14', 
    'abbey', 
    'f', 
    '1937-06-24', 
    'Cancer de la prostate',
    '2023-04-22',
    '59'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '15', 
    'abbie', 
    'f', 
    '1925-01-24', 
    'Troubles addictifs',
    '2023-06-15',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '16', 
    'abby', 
    'f', 
    '1964-06-02', 
    'Troubles psychotiques',
    '2023-10-26',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '17', 
    'abd-al-aziz', 
    'm', 
    '2009-05-10', 
    'Troubles addictifs',
    '2021-10-02',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '18', 
    'abd-allah', 
    'm', 
    '1959-07-09', 
    'Maladies rares',
    '2021-04-05',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '19', 
    'abd-al-malik', 
    'm', 
    '2008-07-28', 
    'Cancer bronchopulmonaire',
    '2021-11-30',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '20', 
    'abd-al-qadir', 
    'm', 
    '2013-12-04', 
    'Maladie de Parkinson',
    '2021-05-16',
    '45'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '21', 
    'abd-al-rahman', 
    'm', 
    '1999-09-18', 
    'Embolie pulmonaire',
    '2022-06-26',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '22', 
    'abdul', 
    'm', 
    '1940-02-17', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-10-01',
    '75'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '23', 
    'abdul-aziz', 
    'm', 
    '1989-01-22', 
    'Insuffisance cardiaque',
    '2022-01-22',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '24', 
    'abdullah', 
    'm', 
    '1984-05-25', 
    'Cancer du sein de la femme',
    '2021-04-15',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '25', 
    'abdul-rahman', 
    'm', 
    '1978-05-11', 
    'Embolie pulmonaire',
    '2022-05-05',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '26', 
    'abe', 
    'm', 
    '2005-08-09', 
    'Accident vasculaire cérébral',
    '2021-10-30',
    '76'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '27', 
    'abednego', 
    'm', 
    '1952-08-08', 
    'Insuffisance cardiaque',
    '2022-01-07',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '28', 
    'abegail', 
    'f', 
    '1996-08-27', 
    'Accident vasculaire cérébral',
    '2022-10-30',
    '46'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '29', 
    'ábel', 
    'm', 
    '1983-12-03', 
    'Cancer bronchopulmonaire',
    '2023-11-02',
    '43'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '30', 
    'abel', 
    'm', 
    '1952-08-06', 
    'Polyarthrite rhumatoïde ',
    '2021-09-13',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '31', 
    'abelone', 
    'f', 
    '1969-06-07', 
    'Cancer du sein de la femme',
    '2021-05-06',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '32', 
    'abena', 
    'f', 
    '1938-09-29', 
    'Maladie valvulaire',
    '2023-01-06',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '33', 
    'abeni', 
    'f', 
    '1938-07-04', 
    'Embolie pulmonaire',
    '2021-10-19',
    '31'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '34', 
    'abhay', 
    'm', 
    '1991-10-06', 
    'Cancer bronchopulmonaire',
    '2021-10-20',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '35', 
    'abiah', 
    'm', 
    '1997-10-06', 
    'Maladie valvulaire',
    '2021-05-11',
    '33'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '36', 
    'abidan', 
    'm', 
    '2001-09-24', 
    'Polyarthrite rhumatoïde ',
    '2023-04-28',
    '67'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '37', 
    'abidemi', 
    'm', 
    '1925-03-31', 
    'Maladies rares',
    '2022-01-14',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '38', 
    'abiel', 
    'm', 
    '1943-02-05', 
    'Troubles psychotiques',
    '2022-04-12',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '39', 
    'abigail', 
    'f', 
    '2002-08-12', 
    'Embolie pulmonaire',
    '2022-04-10',
    '56'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '40', 
    'abigayle', 
    'f', 
    '1992-11-05', 
    'Cancer de la prostate',
    '2023-02-10',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '41', 
    'abihu', 
    'm', 
    '1930-04-29', 
    'Accident vasculaire cérébral',
    '2021-01-10',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '42', 
    'abijah', 
    'm', 
    '1975-10-27', 
    'Myopathie ou myasthénie',
    '2022-03-02',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '43', 
    'abilene', 
    'f', 
    '1959-08-26', 
    'Troubles addictifs',
    '2021-04-22',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '44', 
    'abimael', 
    'm', 
    '2002-05-06', 
    'Cancer bronchopulmonaire',
    '2021-12-23',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '45', 
    'abiram', 
    'm', 
    '1972-03-10', 
    'Embolie pulmonaire',
    '2022-08-13',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '46', 
    'abisai', 
    'm', 
    '1951-03-11', 
    'Cancer colorectal',
    '2021-08-22',
    '75'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '47', 
    'abishag', 
    'f', 
    '1942-02-10', 
    'Maladies rares',
    '2023-07-05',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '48', 
    'abishai', 
    'm', 
    '1932-01-04', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-15',
    '49'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '49', 
    'abital', 
    'f', 
    '1944-01-06', 
    'Cancer bronchopulmonaire',
    '2021-10-09',
    '72'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '50', 
    'abla', 
    'f', 
    '1978-10-08', 
    'Cancer du sein de la femme',
    '2021-01-03',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '51', 
    'abner', 
    'm', 
    '1994-09-06', 
    'Cancer bronchopulmonaire',
    '2022-03-28',
    '48'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '52', 
    'abraham', 
    'm', 
    '1965-10-16', 
    'Mucoviscidose',
    '2021-08-27',
    '92'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '53', 
    'abram', 
    'm', 
    '1962-12-19', 
    'Troubles addictifs',
    '2021-08-13',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '54', 
    'absalom', 
    'm', 
    '1979-01-07', 
    'Cancer du sein de la femme',
    '2023-08-14',
    '85'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '55', 
    'absolon', 
    'm', 
    '1981-03-28', 
    'Troubles psychotiques',
    '2021-12-20',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '56', 
    'acacia', 
    'f', 
    '1944-03-16', 
    'Myopathie ou myasthénie',
    '2021-06-28',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '57', 
    'acacius', 
    'm', 
    '1990-06-04', 
    'Troubles addictifs',
    '2023-04-25',
    '08'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '58', 
    'acantha', 
    'f', 
    '1995-06-23', 
    'Maladie de Parkinson',
    '2022-05-04',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '59', 
    'ace', 
    'm', 
    '1976-08-31', 
    'Cancer du sein de la femme',
    '2023-06-19',
    '55'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '60', 
    'achaicus', 
    'm', 
    '2006-08-22', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-18',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '61', 
    'achan', 
    'm', 
    '1999-07-14', 
    'Accident vasculaire cérébral',
    '2022-11-14',
    '27'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '62', 
    'achieng', 
    'f', 
    '1997-11-17', 
    'Maladie valvulaire',
    '2022-06-07',
    '56'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '63', 
    'achille', 
    'm', 
    '1974-06-15', 
    'Diabète',
    '2021-09-18',
    '40'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '64', 
    'achilles', 
    'm', 
    '1988-11-18', 
    'Cancer de la prostate',
    '2023-02-06',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '65', 
    'achim', 
    'm', 
    '2001-10-25', 
    'Maladie de Parkinson',
    '2022-04-19',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '66', 
    'acke', 
    'm', 
    '1936-09-01', 
    'Diabète',
    '2023-08-17',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '67', 
    'ada', 
    'f', 
    '1959-04-29', 
    'Embolie pulmonaire',
    '2023-08-14',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '68', 
    'adah', 
    'f', 
    '1931-12-19', 
    'Accident vasculaire cérébral',
    '2023-11-17',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '69', 
    'adair', 
    'm', 
    '1932-01-17', 
    'Cancer de la prostate',
    '2022-03-31',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '70', 
    'adalbert', 
    'm', 
    '1925-08-13', 
    'Troubles addictifs',
    '2021-08-06',
    '79'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '71', 
    'adalberto', 
    'm', 
    '1994-05-03', 
    'Insuffisance cardiaque',
    '2021-03-01',
    '84'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '72', 
    'adalheid', 
    'f', 
    '2015-04-24', 
    'Cancer du sein de la femme',
    '2023-08-20',
    '972'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '73', 
    'adalia', 
    'm', 
    '1947-03-19', 
    'Cancer de la prostate',
    '2021-11-30',
    '92'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '74', 
    'ádám', 
    'm', 
    '1988-07-30', 
    'Cancer du sein de la femme',
    '2022-07-17',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '75', 
    'adam', 
    'm', 
    '1968-06-16', 
    'Polyarthrite rhumatoïde ',
    '2021-01-04',
    '55'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '76', 
    'adamina', 
    'f', 
    '1963-10-24', 
    'Troubles psychotiques',
    '2023-12-03',
    '45'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '77', 
    'adamo', 
    'm', 
    '1971-08-27', 
    'Embolie pulmonaire',
    '2022-06-17',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '78', 
    'adán', 
    'm', 
    '2003-11-04', 
    'Polyarthrite rhumatoïde ',
    '2022-07-22',
    '43'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '79', 
    'adão', 
    'm', 
    '1951-08-01', 
    'Maladies inflammatoires chroniques',
    '2022-06-01',
    '67'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '80', 
    'adara', 
    'f', 
    '1952-02-09', 
    'Cancer bronchopulmonaire',
    '2022-08-20',
    '44'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '81', 
    'addie', 
    'f', 
    '1963-06-16', 
    'Maladies rares',
    '2022-09-01',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '82', 
    'addison', 
    'm', 
    '1981-08-14', 
    'Myopathie ou myasthénie',
    '2022-08-06',
    '22'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '83', 
    'addy', 
    'f', 
    '1980-10-03', 
    'Polyarthrite rhumatoïde ',
    '2021-05-29',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '84', 
    'adel', 
    'm', 
    '2008-11-22', 
    'Accident vasculaire cérébral',
    '2021-03-09',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '85', 
    'adela', 
    'f', 
    '2001-02-08', 
    'Myopathie ou myasthénie',
    '2021-04-29',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '86', 
    'adélaïde', 
    'f', 
    '1947-11-07', 
    'Polyarthrite rhumatoïde ',
    '2021-07-11',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '87', 
    'adelaide', 
    'f', 
    '1994-02-07', 
    'Maladies inflammatoires chroniques',
    '2022-01-24',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '88', 
    'adèle', 
    'f', 
    '1975-12-06', 
    'Myopathie ou myasthénie',
    '2021-11-25',
    '02'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '89', 
    'adelheid', 
    'f', 
    '1960-11-17', 
    'Maladies rares',
    '2021-08-17',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '90', 
    'adelia', 
    'f', 
    '2007-03-12', 
    'Maladies inflammatoires chroniques',
    '2021-01-14',
    '59'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '91', 
    'adelina', 
    'f', 
    '1978-02-26', 
    'Cancer de la prostate',
    '2021-03-17',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '92', 
    'adeline', 
    'f', 
    '1979-12-10', 
    'Troubles addictifs',
    '2022-03-06',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '93', 
    'adelle', 
    'f', 
    '1976-09-12', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-05-11',
    '26'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '94', 
    'adelmar', 
    'm', 
    '1940-11-19', 
    'Maladie de Parkinson',
    '2021-12-27',
    '02'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '95', 
    'adem', 
    'm', 
    '2001-08-25', 
    'Cancer colorectal',
    '2022-12-02',
    '27'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '96', 
    'aden', 
    'm', 
    '1941-02-15', 
    'Polyarthrite rhumatoïde ',
    '2021-02-05',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '97', 
    'adena', 
    'f', 
    '1970-12-25', 
    'Accident vasculaire cérébral',
    '2022-07-21',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '98', 
    'adhara', 
    'f', 
    '2005-07-24', 
    'Troubles addictifs',
    '2022-06-13',
    '89'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '99', 
    'adhiambo', 
    'f', 
    '1951-10-29', 
    'Maladies rares',
    '2022-09-10',
    '79'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '100', 
    'adi', 
    'f', 
    '1936-07-16', 
    'Maladie de Parkinson',
    '2022-08-13',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '101', 
    'adil', 
    'm', 
    '1957-04-16', 
    'Cancer colorectal',
    '2023-07-27',
    '971'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '102', 
    'adina', 
    'f', 
    '1989-03-14', 
    'Maladie valvulaire',
    '2023-02-06',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '103', 
    'adino', 
    'm', 
    '1937-10-06', 
    'Cancer du sein de la femme',
    '2023-10-14',
    '94'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '104', 
    'adisa', 
    'm', 
    '1992-07-20', 
    'Accident vasculaire cérébral',
    '2021-07-29',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '105', 
    'aditya', 
    'm', 
    '2011-03-26', 
    'Diabète',
    '2021-08-15',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '106', 
    'adjoa', 
    'f', 
    '2009-11-06', 
    'Cancer bronchopulmonaire',
    '2021-04-18',
    '16'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '107', 
    'adlai', 
    'm', 
    '1997-04-26', 
    'Diabète',
    '2022-02-15',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '108', 
    'adolf', 
    'm', 
    '1989-01-31', 
    'Troubles addictifs',
    '2021-01-24',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '109', 
    'adolfo', 
    'm', 
    '1964-11-10', 
    'Cancer colorectal',
    '2023-02-17',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '110', 
    'adolph', 
    'm', 
    '1944-08-16', 
    'Cancer bronchopulmonaire',
    '2023-02-19',
    '37'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '111', 
    'adolphe', 
    'm', 
    '1978-07-04', 
    'Diabète',
    '2023-08-15',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '112', 
    'adolphus', 
    'm', 
    '1944-01-17', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-11-08',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '113', 
    'adonai', 
    'm', 
    '1968-02-05', 
    'Troubles addictifs',
    '2023-03-08',
    '41'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '114', 
    'adonia', 
    'f', 
    '1945-03-11', 
    'Cancer colorectal',
    '2023-05-17',
    '09'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '115', 
    'adonijah', 
    'm', 
    '1973-06-03', 
    'Maladie valvulaire',
    '2023-04-23',
    '55'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '116', 
    'adonis', 
    'm', 
    '1977-03-23', 
    'Mucoviscidose',
    '2023-08-26',
    '63'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '117', 
    'adora', 
    'f', 
    '1997-08-11', 
    'Cancer de la prostate',
    '2022-07-28',
    '63'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '118', 
    'adorinda', 
    'f', 
    '2014-11-27', 
    'Cancer du sein de la femme',
    '2021-09-28',
    '15'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '119', 
    'adorján', 
    'm', 
    '2017-05-04', 
    'Accident vasculaire cérébral',
    '2023-04-20',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '120', 
    'adrasteia', 
    'f', 
    '1957-11-07', 
    'Cancer de la prostate',
    '2023-07-15',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '121', 
    'adrastos', 
    'm', 
    '1940-02-23', 
    'Mucoviscidose',
    '2021-09-16',
    '87'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '122', 
    'adria', 
    'f', 
    '1976-06-01', 
    'Maladies rares',
    '2023-08-26',
    '08'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '123', 
    'adriaan', 
    'm', 
    '2016-12-26', 
    'Polyarthrite rhumatoïde ',
    '2021-09-14',
    '15'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '124', 
    'adrián', 
    'm', 
    '1969-04-08', 
    'Accident vasculaire cérébral',
    '2022-03-15',
    '22'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '125', 
    'adrian', 
    'm', 
    '1996-03-03', 
    'Polyarthrite rhumatoïde ',
    '2022-05-19',
    '67'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '126', 
    'adriana', 
    'f', 
    '2003-10-04', 
    'Diabète',
    '2023-12-05',
    '24'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '127', 
    'adrianna', 
    'f', 
    '1985-04-06', 
    'Accident vasculaire cérébral',
    '2021-02-07',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '128', 
    'adrianne', 
    'f', 
    '1999-09-14', 
    'Diabète',
    '2021-03-25',
    '44'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '129', 
    'adriano', 
    'm', 
    '1997-03-06', 
    'Cancer colorectal',
    '2023-05-05',
    '75'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '130', 
    'adrien', 
    'm', 
    '1997-08-05', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-07-09',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '131', 
    'adrienn', 
    'f', 
    '1986-02-25', 
    'Myopathie ou myasthénie',
    '2023-06-08',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '132', 
    'adrienne', 
    'f', 
    '2005-12-13', 
    'Maladie de Parkinson',
    '2021-07-24',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '133', 
    'adwoa', 
    'f', 
    '1968-11-19', 
    'Embolie pulmonaire',
    '2021-01-20',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '134', 
    'aegle', 
    'f', 
    '2013-05-15', 
    'Insuffisance cardiaque',
    '2022-05-03',
    '38'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '135', 
    'ælfwine', 
    'm', 
    '1991-12-23', 
    'Troubles addictifs',
    '2022-01-23',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '136', 
    'aella', 
    'f', 
    '1996-11-12', 
    'Troubles psychotiques',
    '2022-09-05',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '137', 
    'ælred', 
    'm', 
    '2000-12-05', 
    'Myopathie ou myasthénie',
    '2021-01-19',
    '40'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '138', 
    'aemilia', 
    'f', 
    '2013-10-12', 
    'Maladies rares',
    '2022-08-24',
    '66'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '139', 
    'aeneas', 
    'm', 
    '2015-11-15', 
    'Cancer bronchopulmonaire',
    '2021-10-21',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '140', 
    'aengus', 
    'm', 
    '1939-07-03', 
    'Insuffisance cardiaque',
    '2021-04-10',
    '49'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '141', 
    'aeolus', 
    'm', 
    '2004-07-10', 
    'Diabète',
    '2021-10-10',
    '90'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '142', 
    'aeron (1)', 
    'm', 
    '1955-10-21', 
    'Mucoviscidose',
    '2023-03-23',
    '49'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '143', 
    'aeron (2)', 
    'f', 
    '2003-01-07', 
    'Mucoviscidose',
    '2022-05-25',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '144', 
    'aeronwen', 
    'f', 
    '1950-11-16', 
    'Cancer de la prostate',
    '2021-03-01',
    '67'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '145', 
    'aeronwy', 
    'f', 
    '1929-08-11', 
    'Cancer colorectal',
    '2021-05-03',
    '87'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '146', 
    'æsc', 
    'm', 
    '1935-03-29', 
    'Cancer de la prostate',
    '2023-04-23',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '147', 
    'aeschylus', 
    'm', 
    '2014-11-08', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-04-07',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '148', 
    'aeson', 
    'm', 
    '1942-10-04', 
    'Myopathie ou myasthénie',
    '2022-06-19',
    '69'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '149', 
    'aesop', 
    'm', 
    '1954-02-10', 
    'Cancer du sein de la femme',
    '2022-11-18',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '150', 
    'æðelbert', 
    'm', 
    '2003-10-18', 
    'Troubles psychotiques',
    '2023-06-11',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '151', 
    'æðelfrid', 
    'm', 
    '1955-11-15', 
    'Maladies rares',
    '2021-01-16',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '152', 
    'æðelmær', 
    'm', 
    '1970-10-15', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-01-28',
    '63'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '153', 
    'æðelred', 
    'm', 
    '2006-08-15', 
    'Troubles addictifs',
    '2022-05-15',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '154', 
    'æðelstan', 
    'm', 
    '1932-11-27', 
    'Polyarthrite rhumatoïde ',
    '2021-11-03',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '155', 
    'æðelþryð', 
    'f', 
    '1927-02-09', 
    'Embolie pulmonaire',
    '2022-12-22',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '156', 
    'afanasi', 
    'm', 
    '1936-07-16', 
    'Insuffisance cardiaque',
    '2022-05-23',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '157', 
    'afanasy', 
    'm', 
    '1946-07-17', 
    'Cancer de la prostate',
    '2022-10-14',
    '16'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '158', 
    'afanen', 
    'f', 
    '1940-06-30', 
    'Maladies rares',
    '2022-10-10',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '159', 
    'afia', 
    'f', 
    '1964-06-15', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-08-09',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '160', 
    'afolabi', 
    'm', 
    '1941-08-03', 
    'Maladie de Parkinson',
    '2021-08-21',
    '52'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '161', 
    'afon', 
    'f', 
    '2015-04-02', 
    'Maladies inflammatoires chroniques',
    '2022-06-19',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '162', 
    'afonso', 
    'm', 
    '1981-09-16', 
    'Maladies inflammatoires chroniques',
    '2022-06-20',
    '19'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '163', 
    'afra', 
    'f', 
    '1983-03-14', 
    'Polyarthrite rhumatoïde ',
    '2022-02-14',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '164', 
    'africa', 
    'f', 
    '2009-03-05', 
    'Polyarthrite rhumatoïde ',
    '2021-12-14',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '165', 
    'afua', 
    'f', 
    '1952-08-12', 
    'Myopathie ou myasthénie',
    '2023-10-13',
    '42'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '166', 
    'agafya', 
    'f', 
    '1957-06-11', 
    'Diabète',
    '2021-10-06',
    '42'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '167', 
    'agamemnon', 
    'm', 
    '2019-01-14', 
    'Maladies rares',
    '2021-05-30',
    '65'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '168', 
    'agape', 
    'f', 
    '1991-07-18', 
    'Maladie valvulaire',
    '2022-05-29',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '169', 
    'agapios', 
    'm', 
    '1949-04-14', 
    'Diabète',
    '2021-10-18',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '170', 
    'agata', 
    'f', 
    '1970-08-04', 
    'Cancer de la prostate',
    '2022-03-07',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '171', 
    'agatha', 
    'f', 
    '1977-09-07', 
    'Cancer du sein de la femme',
    '2021-01-15',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '172', 
    'agathangelos', 
    'f', 
    '1998-04-25', 
    'Cancer du sein de la femme',
    '2022-06-11',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '173', 
    'agathe', 
    'f', 
    '2005-10-28', 
    'Cancer colorectal',
    '2021-10-20',
    '68'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '174', 
    'agathon', 
    'm', 
    '1978-11-13', 
    'Insuffisance cardiaque',
    '2023-02-05',
    '69'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '175', 
    'agaue', 
    'f', 
    '1931-12-17', 
    'Troubles addictifs',
    '2022-11-15',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '176', 
    'aggie', 
    'f', 
    '1951-09-10', 
    'Maladies inflammatoires chroniques',
    '2021-03-25',
    '09'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '177', 
    'aghavni', 
    'f', 
    '1956-04-29', 
    'Mucoviscidose',
    '2021-03-11',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '178', 
    'ági', 
    'f', 
    '1957-08-27', 
    'Cancer de la prostate',
    '2023-04-21',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '179', 
    'aglaia', 
    'f', 
    '1979-03-24', 
    'Troubles addictifs',
    '2021-02-17',
    '60'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '180', 
    'aglaya', 
    'f', 
    '2005-09-19', 
    'Cancer bronchopulmonaire',
    '2021-10-05',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '181', 
    'aglea', 
    'f', 
    '1946-02-05', 
    'Cancer du sein de la femme',
    '2023-02-03',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '182', 
    'ágnes', 
    'f', 
    '1989-02-18', 
    'Troubles psychotiques',
    '2023-06-10',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '183', 
    'agnès', 
    'f', 
    '1991-04-26', 
    'Maladies rares',
    '2022-06-23',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '184', 
    'agnes', 
    'f', 
    '1942-03-20', 
    'Polyarthrite rhumatoïde ',
    '2023-02-10',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '185', 
    'agnese', 
    'f', 
    '1938-11-06', 
    'Embolie pulmonaire',
    '2023-07-13',
    '91'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '186', 
    'agnessa', 
    'f', 
    '1941-08-16', 
    'Cancer de la prostate',
    '2021-04-25',
    '52'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '187', 
    'agneta', 
    'f', 
    '2018-05-04', 
    'Maladies rares',
    '2022-10-01',
    '973'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '188', 
    'agnethe', 
    'f', 
    '2002-11-19', 
    'Cancer de la prostate',
    '2021-11-14',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '189', 
    'agnieszka', 
    'f', 
    '1937-06-06', 
    'Maladie de Parkinson',
    '2022-06-11',
    '32'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '190', 
    'agostina', 
    'f', 
    '1948-03-22', 
    'Accident vasculaire cérébral',
    '2021-10-25',
    '32'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '191', 
    'agostinho', 
    'm', 
    '2003-09-01', 
    'Cancer colorectal',
    '2021-02-10',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '192', 
    'agostino', 
    'm', 
    '2019-01-26', 
    'Troubles addictifs',
    '2021-11-16',
    '94'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '193', 
    'ágoston', 
    'm', 
    '2009-03-21', 
    'Maladie valvulaire',
    '2023-03-18',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '194', 
    'ágota', 
    'f', 
    '2000-05-22', 
    'Cancer colorectal',
    '2023-10-11',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '195', 
    'agrafena', 
    'f', 
    '1971-01-17', 
    'Cancer bronchopulmonaire',
    '2021-07-20',
    '79'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '196', 
    'agrippa', 
    'm', 
    '1998-10-03', 
    'Embolie pulmonaire',
    '2022-06-19',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '197', 
    'agrippina', 
    'f', 
    '1954-07-03', 
    'Cancer de la prostate',
    '2021-07-09',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '198', 
    'agrona', 
    'f', 
    '1927-10-16', 
    'Embolie pulmonaire',
    '2023-06-28',
    '90'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '199', 
    'águeda', 
    'f', 
    '2004-05-12', 
    'Maladie de Parkinson',
    '2022-05-22',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '200', 
    'agustín', 
    'm', 
    '1982-06-24', 
    'Maladie de Parkinson',
    '2022-01-03',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '201', 
    'ah', 
    'm', 
    '1940-03-16', 
    'Troubles addictifs',
    '2021-10-02',
    '72'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '202', 
    'ahab', 
    'm', 
    '2012-02-06', 
    'Cancer du sein de la femme',
    '2021-01-17',
    '04'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '203', 
    'aharon', 
    'm', 
    '1960-03-07', 
    'Maladies rares',
    '2021-07-09',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '204', 
    'ahmad', 
    'm', 
    '1945-10-31', 
    'Mucoviscidose',
    '2021-10-28',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '205', 
    'ahmed', 
    'm', 
    '1975-02-13', 
    'Embolie pulmonaire',
    '2022-05-01',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '206', 
    'ahmet', 
    'm', 
    '2006-04-21', 
    'Insuffisance cardiaque',
    '2021-02-04',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '207', 
    'ahriman', 
    'm', 
    '1988-09-14', 
    'Cancer du sein de la femme',
    '2022-09-16',
    '60'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '208', 
    'ahtahkakoop', 
    'm', 
    '2007-11-20', 
    'Cancer du sein de la femme',
    '2021-01-23',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '209', 
    'ahura mazda', 
    'm', 
    '1971-02-01', 
    'Maladie de Parkinson',
    '2022-11-14',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '210', 
    'ahuva', 
    'f', 
    '1997-10-15', 
    'Embolie pulmonaire',
    '2023-06-24',
    '87'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '211', 
    'ai (1)', 
    'f', 
    '2009-08-25', 
    'Insuffisance cardiaque',
    '2022-11-14',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '212', 
    'ai (2)', 
    'f', 
    '2012-07-28', 
    'Embolie pulmonaire',
    '2021-06-25',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '213', 
    'aias', 
    'm', 
    '1989-12-15', 
    'Mucoviscidose',
    '2023-08-10',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '214', 
    'aida', 
    'f', 
    '1982-03-15', 
    'Cancer bronchopulmonaire',
    '2021-08-25',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '215', 
    'aidan', 
    'm', 
    '2001-11-04', 
    'Accident vasculaire cérébral',
    '2023-06-03',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '216', 
    'aiden', 
    'm', 
    '1978-03-11', 
    'Maladies rares',
    '2022-03-20',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '217', 
    'aignéis', 
    'f', 
    '1965-05-14', 
    'Cancer colorectal',
    '2022-12-14',
    '973'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '218', 
    'aikaterine', 
    'f', 
    '1961-08-04', 
    'Cancer du sein de la femme',
    '2021-10-14',
    '33'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '219', 
    'ailbhe', 
    'm', 
    '1992-12-30', 
    'Maladies inflammatoires chroniques',
    '2022-08-25',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '220', 
    'aileas', 
    'f', 
    '1999-07-03', 
    'Polyarthrite rhumatoïde ',
    '2021-03-27',
    '52'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '221', 
    'aileen', 
    'f', 
    '1958-03-09', 
    'Myopathie ou myasthénie',
    '2021-09-24',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '222', 
    'ailill', 
    'm', 
    '1987-07-19', 
    'Troubles psychotiques',
    '2022-10-14',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '223', 
    'ailín', 
    'm', 
    '1956-05-06', 
    'Maladies inflammatoires chroniques',
    '2021-10-25',
    '42'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '224', 
    'ailís', 
    'f', 
    '1988-06-06', 
    'Troubles psychotiques',
    '2021-07-19',
    '80'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '225', 
    'ailpein', 
    'm', 
    '2013-06-18', 
    'Cancer de la prostate',
    '2023-07-09',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '226', 
    'ailsa', 
    'f', 
    '1940-09-11', 
    'Diabète',
    '2021-01-09',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '227', 
    'aimé', 
    'm', 
    '2006-07-19', 
    'Mucoviscidose',
    '2021-03-23',
    '48'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '228', 
    'aimée', 
    'f', 
    '1984-08-07', 
    'Maladies rares',
    '2023-05-16',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '229', 
    'aimo', 
    'm', 
    '1981-01-19', 
    'Troubles psychotiques',
    '2022-03-01',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '230', 
    'aina', 
    'f', 
    '2016-07-30', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-06-24',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '231', 
    'aindrea', 
    'm', 
    '1956-01-01', 
    'Myopathie ou myasthénie',
    '2021-10-30',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '232', 
    'aindréas', 
    'm', 
    '1931-07-09', 
    'Cancer colorectal',
    '2021-09-03',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '233', 
    'aindriú', 
    'm', 
    '1990-08-12', 
    'Cancer de la prostate',
    '2022-04-26',
    '69'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '234', 
    'áine', 
    'f', 
    '1988-02-17', 
    'Accident vasculaire cérébral',
    '2021-06-19',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '235', 
    'aingeal', 
    'f', 
    '1979-12-02', 
    'Mucoviscidose',
    '2023-11-18',
    '95'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '236', 
    'aino', 
    'f', 
    '2004-08-23', 
    'Maladie valvulaire',
    '2022-08-13',
    '03'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '237', 
    'ainsley', 
    'm', 
    '1943-10-06', 
    'Maladies inflammatoires chroniques',
    '2022-06-03',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '238', 
    'ainslie', 
    'm', 
    '1962-10-13', 
    'Maladie de Parkinson',
    '2023-12-03',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '239', 
    'aintzane', 
    'f', 
    '1975-12-08', 
    'Cancer du sein de la femme',
    '2021-08-28',
    '95'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '240', 
    'aiolos', 
    'm', 
    '1984-05-29', 
    'Maladies inflammatoires chroniques',
    '2023-02-16',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '241', 
    'aisha', 
    'f', 
    '1945-01-14', 
    'Embolie pulmonaire',
    '2021-03-07',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '242', 
    'aislin', 
    'f', 
    '1932-04-29', 
    'Mucoviscidose',
    '2021-11-12',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '243', 
    'aisling', 
    'f', 
    '1931-12-31', 
    'Troubles addictifs',
    '2023-02-13',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '244', 
    'aislinn', 
    'f', 
    '1960-07-28', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-04-13',
    '15'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '245', 
    'aithne', 
    'f', 
    '1980-08-24', 
    'Accident vasculaire cérébral',
    '2023-10-15',
    '52'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '246', 
    'aitor', 
    'm', 
    '1975-04-16', 
    'Cancer du sein de la femme',
    '2023-03-13',
    '91'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '247', 
    'ajax', 
    'm', 
    '1985-12-01', 
    'Polyarthrite rhumatoïde ',
    '2021-06-03',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '248', 
    'ajeet', 
    'm', 
    '1950-09-09', 
    'Cancer colorectal',
    '2022-04-04',
    '59'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '249', 
    'ajit', 
    'm', 
    '1959-09-26', 
    'Cancer colorectal',
    '2022-04-06',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '250', 
    'ajith', 
    'm', 
    '2007-02-04', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2022-08-20',
    '80'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '251', 
    'akakios', 
    'm', 
    '1953-09-16', 
    'Maladies rares',
    '2022-06-02',
    '35'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '252', 
    'akamu', 
    'm', 
    '1956-12-11', 
    'Myopathie ou myasthénie',
    '2022-05-25',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '253', 
    'akanksha', 
    'f', 
    '1974-11-21', 
    'Myopathie ou myasthénie',
    '2021-12-27',
    '75'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '254', 
    'akeem', 
    'm', 
    '2018-05-30', 
    'Cancer colorectal',
    '2023-12-11',
    '19'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '255', 
    'akemi', 
    'f', 
    '1971-04-04', 
    'Maladies inflammatoires chroniques',
    '2023-04-08',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '256', 
    'akhil', 
    'm', 
    '1972-05-19', 
    'Mucoviscidose',
    '2023-08-18',
    '89'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '257', 
    'aki', 
    'm', 
    '1929-05-17', 
    'Maladie de Parkinson',
    '2022-07-09',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '258', 
    'akiko', 
    'f', 
    '1982-01-19', 
    'Insuffisance cardiaque',
    '2022-10-07',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '259', 
    'akilah', 
    'f', 
    '2007-06-19', 
    'Cancer de la prostate',
    '2022-06-28',
    '69'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '260', 
    'akilina', 
    'f', 
    '1957-10-21', 
    'Mucoviscidose',
    '2023-04-25',
    '30'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '261', 
    'akim', 
    'm', 
    '1932-11-12', 
    'Maladie valvulaire',
    '2022-07-31',
    '46'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '262', 
    'akinyi', 
    'f', 
    '1942-07-24', 
    'Maladies inflammatoires chroniques',
    '2022-10-30',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '263', 
    'akio', 
    'm', 
    '1988-06-05', 
    'Embolie pulmonaire',
    '2021-09-08',
    '85'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '264', 
    'akira', 
    'm', 
    '2017-01-20', 
    'Cancer bronchopulmonaire',
    '2023-04-02',
    '19'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '265', 
    'akiva', 
    'm', 
    '2013-12-22', 
    'Maladies inflammatoires chroniques',
    '2021-04-21',
    '38'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '266', 
    'akoni', 
    'm', 
    '1943-12-19', 
    'Myopathie ou myasthénie',
    '2022-06-04',
    '87'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '267', 
    'akosua', 
    'f', 
    '1958-04-07', 
    'Maladie valvulaire',
    '2022-11-29',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '268', 
    'aksel', 
    'm', 
    '1991-01-27', 
    'Maladies inflammatoires chroniques',
    '2021-02-05',
    '19'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '269', 
    'aksinya', 
    'f', 
    '1988-09-08', 
    'Troubles addictifs',
    '2023-05-05',
    '64'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '270', 
    'aku', 
    'm', 
    '1937-03-14', 
    'Cancer du sein de la femme',
    '2021-12-16',
    '10'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '271', 
    'akua', 
    'f', 
    '1948-03-04', 
    'Cancer du sein de la femme',
    '2022-04-23',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '272', 
    'akulina', 
    'f', 
    '1984-10-20', 
    'Troubles psychotiques',
    '2022-11-23',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '273', 
    'al', 
    'm', 
    '1950-11-10', 
    'Diabète',
    '2022-07-19',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '274', 
    'alaba', 
    'f', 
    '1941-10-22', 
    'Maladies inflammatoires chroniques',
    '2022-04-26',
    '12'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '275', 
    'alain', 
    'm', 
    '1990-04-21', 
    'Maladie de Parkinson',
    '2023-08-03',
    '81'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '276', 
    'alaina', 
    'f', 
    '1946-05-30', 
    'Maladie de Parkinson',
    '2021-05-03',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '277', 
    'alan', 
    'm', 
    '2002-02-23', 
    'Cancer colorectal',
    '2021-07-12',
    '16'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '278', 
    'alana', 
    'f', 
    '2010-07-22', 
    'Cancer de la prostate',
    '2022-07-21',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '279', 
    'alanis', 
    'f', 
    '1971-08-03', 
    'Embolie pulmonaire',
    '2022-10-22',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '280', 
    'alanna', 
    'f', 
    '1993-02-13', 
    'Diabète',
    '2022-01-23',
    '44'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '281', 
    'alannah', 
    'f', 
    '1944-08-22', 
    'Troubles psychotiques',
    '2022-07-23',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '282', 
    'alannis', 
    'f', 
    '1940-09-16', 
    'Mucoviscidose',
    '2021-06-20',
    '41'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '283', 
    'alaois', 
    'm', 
    '1965-01-27', 
    'Embolie pulmonaire',
    '2021-07-17',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '284', 
    'alaric', 
    'm', 
    '1982-08-06', 
    'Mucoviscidose',
    '2022-11-30',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '285', 
    'alasdair', 
    'm', 
    '1962-03-11', 
    'Polyarthrite rhumatoïde ',
    '2023-11-18',
    '63'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '286', 
    'alastair', 
    'm', 
    '1930-06-03', 
    'Maladies rares',
    '2022-10-29',
    '10'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '287', 
    'alastar', 
    'm', 
    '1926-06-10', 
    'Maladies inflammatoires chroniques',
    '2023-09-17',
    '68'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '288', 
    'alastríona', 
    'f', 
    '1929-04-02', 
    'Troubles addictifs',
    '2023-12-24',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '289', 
    'alayna', 
    'f', 
    '1938-03-21', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-02-23',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '290', 
    'alba', 
    'f', 
    '2014-07-06', 
    'Troubles psychotiques',
    '2022-07-24',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '291', 
    'alban', 
    'm', 
    '1967-11-18', 
    'Insuffisance cardiaque',
    '2022-07-22',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '292', 
    'alberic', 
    'm', 
    '1976-11-24', 
    'Maladie de Parkinson',
    '2022-02-20',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '293', 
    'albert', 
    'm', 
    '1999-01-20', 
    'Troubles addictifs',
    '2023-09-27',
    '30'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '294', 
    'alberta', 
    'f', 
    '1950-10-22', 
    'Polyarthrite rhumatoïde ',
    '2021-01-09',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '295', 
    'albertina', 
    'f', 
    '1996-03-19', 
    'Cancer du sein de la femme',
    '2023-04-07',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '296', 
    'albertine', 
    'f', 
    '1955-09-04', 
    'Embolie pulmonaire',
    '2022-05-12',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '297', 
    'alberto', 
    'm', 
    '1983-07-19', 
    'Troubles addictifs',
    '2022-01-09',
    '56'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '298', 
    'albina', 
    'f', 
    '1935-06-03', 
    'Insuffisance cardiaque',
    '2021-10-15',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '299', 
    'albrecht', 
    'm', 
    '2003-01-03', 
    'Accident vasculaire cérébral',
    '2023-06-08',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '300', 
    'alby', 
    'm', 
    '1963-10-12', 
    'Embolie pulmonaire',
    '2023-05-23',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '301', 
    'alcaeus', 
    'm', 
    '1948-08-22', 
    'Cancer du sein de la femme',
    '2023-03-17',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '302', 
    'alcippe', 
    'f', 
    '1949-08-01', 
    'Cancer colorectal',
    '2023-02-13',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '303', 
    'alcyone', 
    'f', 
    '1957-09-10', 
    'Maladies rares',
    '2021-09-03',
    '24'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '304', 
    'alden', 
    'm', 
    '2011-03-29', 
    'Cancer de la prostate',
    '2021-04-09',
    '80'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '305', 
    'aldo', 
    'm', 
    '1933-09-21', 
    'Maladie de Parkinson',
    '2023-11-30',
    '37'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '306', 
    'aldous', 
    'm', 
    '1968-02-18', 
    'Myopathie ou myasthénie',
    '2022-04-04',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '307', 
    'aldrick', 
    'm', 
    '2002-02-08', 
    'Maladies inflammatoires chroniques',
    '2023-10-30',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '308', 
    'alea', 
    'f', 
    '1928-07-14', 
    'Myopathie ou myasthénie',
    '2021-03-29',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '309', 
    'alease', 
    'f', 
    '1997-07-28', 
    'Cancer du sein de la femme',
    '2022-09-12',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '310', 
    'alec', 
    'm', 
    '2009-11-10', 
    'Maladies inflammatoires chroniques',
    '2022-02-25',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '311', 
    'alechjo', 
    'm', 
    '2007-11-24', 
    'Cancer de la prostate',
    '2021-09-12',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '312', 
    'aled', 
    'm', 
    '1972-02-12', 
    'Maladies rares',
    '2023-03-07',
    '971'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '313', 
    'aleesha', 
    'f', 
    '2001-06-29', 
    'Troubles psychotiques',
    '2023-04-05',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '314', 
    'aleit', 
    'f', 
    '1994-12-23', 
    'Accident vasculaire cérébral',
    '2023-05-25',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '315', 
    'alejandra', 
    'f', 
    '1981-09-23', 
    'Cancer de la prostate',
    '2022-08-04',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '316', 
    'alejandro', 
    'm', 
    '1983-09-26', 
    'Maladie de Parkinson',
    '2023-05-21',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '317', 
    'alejo', 
    'm', 
    '2008-03-24', 
    'Accident vasculaire cérébral',
    '2021-08-01',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '318', 
    'aleksandar', 
    'm', 
    '1941-02-07', 
    'Cancer du sein de la femme',
    '2022-08-24',
    '31'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '319', 
    'aleksander', 
    'm', 
    '1932-07-28', 
    'Embolie pulmonaire',
    '2023-01-05',
    '33'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '320', 
    'aleksandr', 
    'm', 
    '1925-06-23', 
    'Troubles psychotiques',
    '2021-05-29',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '321', 
    'aleksandra', 
    'f', 
    '1966-05-04', 
    'Maladies inflammatoires chroniques',
    '2023-08-19',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '322', 
    'aleksandrina', 
    'f', 
    '1997-07-29', 
    'Maladie valvulaire',
    '2022-09-25',
    '89'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '323', 
    'aleksandro', 
    'm', 
    '1957-10-30', 
    'Maladie valvulaire',
    '2023-03-29',
    '46'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '324', 
    'aleksanteri', 
    'm', 
    '1997-10-23', 
    'Mucoviscidose',
    '2023-01-07',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '325', 
    'aleksei', 
    'm', 
    '1983-04-13', 
    'Accident vasculaire cérébral',
    '2023-03-30',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '326', 
    'aleksi', 
    'm', 
    '1963-07-27', 
    'Maladie valvulaire',
    '2022-09-10',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '327', 
    'alene', 
    'f', 
    '1982-06-26', 
    'Cancer du sein de la femme',
    '2022-02-13',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '328', 
    'alenka', 
    'f', 
    '1989-03-24', 
    'Cancer bronchopulmonaire',
    '2021-10-23',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '329', 
    'ales', 
    'm', 
    '2019-11-04', 
    'Embolie pulmonaire',
    '2023-12-05',
    '16'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '330', 
    'alesha', 
    'f', 
    '1939-10-23', 
    'Embolie pulmonaire',
    '2023-09-01',
    '30'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '331', 
    'alessa', 
    'f', 
    '1989-11-24', 
    'Diabète',
    '2022-09-07',
    '81'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '332', 
    'alessandra', 
    'f', 
    '1970-10-28', 
    'Myopathie ou myasthénie',
    '2023-08-02',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '333', 
    'alessandro', 
    'm', 
    '1966-05-17', 
    'Maladies rares',
    '2023-04-24',
    '68'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '334', 
    'alessia', 
    'f', 
    '1934-10-21', 
    'Cancer bronchopulmonaire',
    '2021-09-06',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '335', 
    'alessio', 
    'm', 
    '1934-07-28', 
    'Cancer colorectal',
    '2021-04-01',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '336', 
    'aleta', 
    'f', 
    '1935-02-27', 
    'Polyarthrite rhumatoïde ',
    '2023-04-07',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '337', 
    'aletha', 
    'f', 
    '1937-10-10', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-02-23',
    '38'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '338', 
    'alethea', 
    'f', 
    '1998-02-11', 
    'Troubles addictifs',
    '2023-05-11',
    '62'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '339', 
    'alex', 
    'm', 
    '1956-03-09', 
    'Troubles addictifs',
    '2023-08-21',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '340', 
    'alexa', 
    'f', 
    '1934-03-18', 
    'Maladies inflammatoires chroniques',
    '2021-05-07',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '341', 
    'alexander', 
    'm', 
    '1958-12-16', 
    'Cancer colorectal',
    '2021-04-28',
    '43'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '342', 
    'alexandr', 
    'm', 
    '2004-01-22', 
    'Troubles addictifs',
    '2022-12-25',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '343', 
    'alexandra', 
    'f', 
    '1991-12-06', 
    'Cancer du sein de la femme',
    '2022-09-16',
    '04'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '344', 
    'alexandre', 
    'm', 
    '1969-07-16', 
    'Maladie valvulaire',
    '2021-07-27',
    '79'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '345', 
    'alexandrea', 
    'f', 
    '2018-01-28', 
    'Cancer du sein de la femme',
    '2021-06-30',
    '01'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '346', 
    'alexandria', 
    'f', 
    '2017-03-15', 
    'Polyarthrite rhumatoïde ',
    '2022-07-07',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '347', 
    'alexandrie', 
    'f', 
    '1979-09-12', 
    'Polyarthrite rhumatoïde ',
    '2022-01-28',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '348', 
    'alexandrina', 
    'f', 
    '1941-12-13', 
    'Accident vasculaire cérébral',
    '2022-05-26',
    '971'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '349', 
    'alexandros', 
    'm', 
    '1999-01-01', 
    'Maladies rares',
    '2023-06-19',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '350', 
    'alexandru', 
    'm', 
    '1991-05-06', 
    'Polyarthrite rhumatoïde ',
    '2022-08-24',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '351', 
    'alexei', 
    'm', 
    '1963-10-25', 
    'Embolie pulmonaire',
    '2021-07-30',
    '59'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '352', 
    'alexej', 
    'm', 
    '2018-06-14', 
    'Mucoviscidose',
    '2021-03-16',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '353', 
    'alexia', 
    'f', 
    '1971-08-04', 
    'Polyarthrite rhumatoïde ',
    '2023-03-10',
    '13'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '354', 
    'alexina', 
    'f', 
    '2013-08-01', 
    'Maladie de Parkinson',
    '2021-12-10',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '355', 
    'alexis (1)', 
    'm', 
    '2005-05-13', 
    'Insuffisance cardiaque',
    '2023-01-17',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '356', 
    'alexis (2)', 
    'f', 
    '1956-08-20', 
    'Diabète',
    '2023-03-14',
    '41'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '357', 
    'alexius', 
    'm', 
    '1952-05-17', 
    'Troubles psychotiques',
    '2022-03-31',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '358', 
    'alexus', 
    'f', 
    '1984-07-07', 
    'Polyarthrite rhumatoïde ',
    '2022-01-19',
    '81'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '359', 
    'alf', 
    'm', 
    '2017-11-12', 
    'Maladies inflammatoires chroniques',
    '2023-05-10',
    '91'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '360', 
    'alfeo', 
    'm', 
    '1989-10-16', 
    'Mucoviscidose',
    '2021-07-21',
    '45'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '361', 
    'alfhild', 
    'f', 
    '1936-01-28', 
    'Maladie de Parkinson',
    '2021-11-30',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '362', 
    'alfons', 
    'm', 
    '1950-09-15', 
    'Embolie pulmonaire',
    '2022-03-28',
    '48'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '363', 
    'alfonsina', 
    'f', 
    '2015-07-08', 
    'Troubles psychotiques',
    '2021-05-23',
    '07'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '364', 
    'alfonso', 
    'm', 
    '1953-09-14', 
    'Embolie pulmonaire',
    '2021-01-16',
    '25'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '365', 
    'alfréd', 
    'm', 
    '1981-12-03', 
    'Polyarthrite rhumatoïde ',
    '2021-07-21',
    '94'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '366', 
    'alfred', 
    'm', 
    '1971-02-13', 
    'Polyarthrite rhumatoïde ',
    '2022-02-24',
    '56'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '367', 
    'alfreda', 
    'f', 
    '1932-10-23', 
    'Cancer colorectal',
    '2022-08-24',
    '78'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '368', 
    'alfredo', 
    'm', 
    '1938-01-13', 
    'Mucoviscidose',
    '2021-04-26',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '369', 
    'alfsigr', 
    'f', 
    '1984-04-05', 
    'Mucoviscidose',
    '2021-05-03',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '370', 
    'algar', 
    'm', 
    '2014-08-25', 
    'Maladie de Parkinson',
    '2022-02-06',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '371', 
    'alger', 
    'm', 
    '2013-04-28', 
    'Maladies rares',
    '2022-12-14',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '372', 
    'algernon', 
    'm', 
    '1958-09-18', 
    'Accident vasculaire cérébral',
    '2021-12-09',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '373', 
    'ali', 
    'm', 
    '1961-05-08', 
    'Troubles psychotiques',
    '2021-10-05',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '374', 
    'alia', 
    'f', 
    '1949-08-18', 
    'Troubles addictifs',
    '2022-02-04',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '375', 
    'aliah', 
    'f', 
    '2008-07-01', 
    'Troubles addictifs',
    '2021-04-19',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '376', 
    'alice', 
    'f', 
    '2002-03-04', 
    'Cancer du sein de la femme',
    '2022-12-10',
    '976'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '377', 
    'alicia', 
    'f', 
    '1990-03-28', 
    'Insuffisance cardiaque',
    '2022-10-01',
    '53'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '378', 
    'alida', 
    'f', 
    '1986-01-26', 
    'Cancer colorectal',
    '2022-07-05',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '379', 
    'aliisa', 
    'f', 
    '1934-09-14', 
    'Accident vasculaire cérébral',
    '2023-12-16',
    '26'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '380', 
    'alin', 
    'm', 
    '2012-05-24', 
    'Cancer du sein de la femme',
    '2023-05-20',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '381', 
    'alina (1)', 
    'f', 
    '1993-07-09', 
    'Cancer bronchopulmonaire',
    '2023-02-28',
    '32'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '382', 
    'alina (2)', 
    'f', 
    '1943-05-02', 
    'Polyarthrite rhumatoïde ',
    '2022-12-18',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '383', 
    'aline', 
    'f', 
    '1953-08-07', 
    'Cancer bronchopulmonaire',
    '2023-09-20',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '384', 
    'alis', 
    'f', 
    '1933-04-01', 
    'Maladies rares',
    '2022-10-01',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '385', 
    'alisa', 
    'f', 
    '1965-04-18', 
    'Polyarthrite rhumatoïde ',
    '2021-04-16',
    '2A'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '386', 
    'alisha', 
    'f', 
    '1981-07-24', 
    'Accident vasculaire cérébral',
    '2021-12-12',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '387', 
    'alisia', 
    'f', 
    '1951-07-12', 
    'Polyarthrite rhumatoïde ',
    '2022-09-04',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '388', 
    'alison', 
    'f', 
    '1989-03-06', 
    'Maladie valvulaire',
    '2022-03-23',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '389', 
    'alissa', 
    'f', 
    '1960-06-10', 
    'Cancer du sein de la femme',
    '2021-09-16',
    '26'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '390', 
    'alistair', 
    'm', 
    '1947-05-14', 
    'Insuffisance cardiaque',
    '2023-01-06',
    '23'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '391', 
    'alister', 
    'm', 
    '1985-02-02', 
    'Cancer du sein de la femme',
    '2022-02-09',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '392', 
    'alisya', 
    'f', 
    '1977-07-17', 
    'Embolie pulmonaire',
    '2021-05-05',
    '49'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '393', 
    'alix', 
    'm', 
    '1954-12-06', 
    'Cancer du sein de la femme',
    '2022-03-01',
    '45'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '394', 
    'aliyah', 
    'f', 
    '1963-08-26', 
    'Myopathie ou myasthénie',
    '2023-05-27',
    '973'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '395', 
    'aliz', 
    'f', 
    '1998-05-12', 
    'Maladies inflammatoires chroniques',
    '2021-04-17',
    '92'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '396', 
    'aliza', 
    'f', 
    '1982-11-17', 
    'Myopathie ou myasthénie',
    '2023-11-02',
    '81'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '397', 
    'allan', 
    'm', 
    '1991-03-01', 
    'Maladie valvulaire',
    '2022-01-06',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '398', 
    'allannah', 
    'f', 
    '1999-07-07', 
    'Embolie pulmonaire',
    '2021-06-12',
    '63'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '399', 
    'allegra', 
    'f', 
    '1983-04-26', 
    'Troubles addictifs',
    '2022-03-09',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '400', 
    'allegria', 
    'f', 
    '1960-05-24', 
    'Accident vasculaire cérébral',
    '2022-08-08',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '401', 
    'allen', 
    'm', 
    '1975-11-18', 
    'Diabète',
    '2023-11-26',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '402', 
    'allie', 
    'f', 
    '1973-01-09', 
    'Maladies inflammatoires chroniques',
    '2021-07-31',
    '80'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '403', 
    'allison', 
    'f', 
    '1927-02-11', 
    'Maladies inflammatoires chroniques',
    '2021-08-08',
    '09'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '404', 
    'allon', 
    'm', 
    '1954-03-07', 
    'Troubles psychotiques',
    '2023-01-21',
    '09'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '405', 
    'ally', 
    'f', 
    '2019-07-27', 
    'Maladies rares',
    '2021-10-19',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '406', 
    'allycia', 
    'f', 
    '1947-03-18', 
    'Maladies inflammatoires chroniques',
    '2021-07-28',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '407', 
    'allyn', 
    'm', 
    '1968-01-16', 
    'Cancer bronchopulmonaire',
    '2023-03-10',
    '33'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '408', 
    'allyson', 
    'f', 
    '1955-02-18', 
    'Troubles psychotiques',
    '2023-10-26',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '409', 
    'alma', 
    'f', 
    '2004-11-13', 
    'Cancer bronchopulmonaire',
    '2022-02-14',
    '88'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '410', 
    'almas', 
    'f', 
    '1959-07-08', 
    'Accident vasculaire cérébral',
    '2022-09-21',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '411', 
    'almira', 
    'f', 
    '1951-04-23', 
    'Diabète',
    '2022-12-14',
    '54'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '412', 
    'almudena', 
    'f', 
    '1948-03-31', 
    'Myopathie ou myasthénie',
    '2023-06-26',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '413', 
    'alodia', 
    'f', 
    '1980-06-30', 
    'Cancer colorectal',
    '2021-08-19',
    '92'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '414', 
    'alois', 
    'm', 
    '1958-09-20', 
    'Cancer colorectal',
    '2022-04-01',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '415', 
    'aloisia', 
    'f', 
    '2015-04-11', 
    'Cancer de la prostate',
    '2022-07-27',
    '82'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '416', 
    'aloisio', 
    'm', 
    '1930-04-29', 
    'Accident vasculaire cérébral',
    '2023-04-03',
    '46'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '417', 
    'alojz', 
    'm', 
    '1995-04-13', 
    'Cancer bronchopulmonaire',
    '2021-10-11',
    '61'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '418', 
    'alon', 
    'm', 
    '1983-06-26', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-06-18',
    '72'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '419', 
    'alondra', 
    'f', 
    '1955-08-14', 
    'Diabète',
    '2022-07-05',
    '52'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '420', 
    'alonso', 
    'm', 
    '2017-06-13', 
    'Maladie de Parkinson',
    '2022-10-21',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '421', 
    'alonzo', 
    'm', 
    '1928-11-13', 
    'Polyarthrite rhumatoïde ',
    '2023-07-19',
    '971'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '422', 
    'aloysius', 
    'm', 
    '2018-05-21', 
    'Maladie de Parkinson',
    '2022-08-13',
    '2B'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '423', 
    'alp', 
    'm', 
    '2013-01-30', 
    'Maladies rares',
    '2023-02-12',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '424', 
    'alpertti', 
    'm', 
    '1977-03-26', 
    'Troubles addictifs',
    '2021-02-17',
    '77'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '425', 
    'alpha', 
    'm', 
    '1978-09-23', 
    'Cancer colorectal',
    '2022-04-10',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '426', 
    'alphaeus', 
    'm', 
    '2006-08-14', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-10-06',
    '35'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '427', 
    'alphonse', 
    'm', 
    '1981-04-24', 
    'Troubles psychotiques',
    '2023-07-03',
    '47'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '428', 
    'alphonsine', 
    'f', 
    '1935-11-21', 
    'Mucoviscidose',
    '2023-02-28',
    '38'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '429', 
    'alphonso', 
    'm', 
    '2006-11-16', 
    'Maladies inflammatoires chroniques',
    '2022-04-17',
    '15'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '430', 
    'alphonsus', 
    'm', 
    '2017-04-28', 
    'Cancer colorectal',
    '2022-03-22',
    '09'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '431', 
    'alphonzo', 
    'm', 
    '1950-01-18', 
    'Mucoviscidose',
    '2022-04-13',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '432', 
    'alpin', 
    'm', 
    '2015-01-09', 
    'Maladie valvulaire',
    '2023-06-26',
    '44'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '433', 
    'alta', 
    'f', 
    '1925-01-17', 
    'Cancer bronchopulmonaire',
    '2022-11-25',
    '35'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '434', 
    'altan', 
    'm', 
    '2007-11-28', 
    'Cancer bronchopulmonaire',
    '2021-06-30',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '435', 
    'alte', 
    'f', 
    '1935-10-07', 
    'Insuffisance cardiaque',
    '2021-02-06',
    '21'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '436', 
    'alter', 
    'm', 
    '1931-02-27', 
    'Cancer colorectal',
    '2022-09-02',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '437', 
    'althea', 
    'f', 
    '1949-12-04', 
    'Myopathie ou myasthénie',
    '2021-09-18',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '438', 
    'alton', 
    'm', 
    '1927-04-01', 
    'Maladie de Parkinson',
    '2021-07-30',
    '18'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '439', 
    'aludra', 
    'f', 
    '1940-07-13', 
    'Insuffisance cardiaque',
    '2022-10-02',
    '30'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '440', 
    'alun', 
    'm', 
    '1977-01-28', 
    'Maladie valvulaire',
    '2023-09-20',
    '83'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '441', 
    'alva', 
    'm', 
    '1973-01-20', 
    'Troubles psychotiques',
    '2021-04-13',
    '70'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '442', 
    'alvah', 
    'm', 
    '1958-09-26', 
    'Myopathie ou myasthénie',
    '2022-05-09',
    '72'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '443', 
    'alvar', 
    'm', 
    '1937-10-29', 
    'Cancer bronchopulmonaire',
    '2021-07-16',
    '65'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '444', 
    'álvaro', 
    'm', 
    '1934-03-08', 
    'Cancer de la prostate',
    '2023-09-16',
    '19'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '445', 
    'alvena', 
    'f', 
    '1987-07-19', 
    'Cancer du sein de la femme',
    '2023-05-09',
    '04'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '446', 
    'alvilda', 
    'f', 
    '1927-05-20', 
    'Mucoviscidose',
    '2021-06-07',
    '40'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '447', 
    'alvin', 
    'm', 
    '1943-05-01', 
    'Cancer du sein de la femme',
    '2023-11-27',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '448', 
    'alvina', 
    'f', 
    '1955-05-23', 
    'Cancer colorectal',
    '2023-06-23',
    '46'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '449', 
    'alvis', 
    'm', 
    '1980-10-14', 
    'Cancer du sein de la femme',
    '2021-12-15',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '450', 
    'alwilda', 
    'f', 
    '1962-05-16', 
    'Troubles addictifs',
    '2022-01-09',
    '16'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '451', 
    'alwyn', 
    'm', 
    '2012-07-29', 
    'Cancer bronchopulmonaire',
    '2021-11-30',
    '43'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '452', 
    'alya', 
    'f', 
    '1985-06-06', 
    'Embolie pulmonaire',
    '2021-03-24',
    '40'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '453', 
    'alyce', 
    'f', 
    '1943-10-10', 
    'Troubles addictifs',
    '2022-04-20',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '454', 
    'alyona', 
    'f', 
    '1955-04-08', 
    'Diabète',
    '2022-04-23',
    '79'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '455', 
    'alys', 
    'f', 
    '1976-03-05', 
    'Maladies inflammatoires chroniques',
    '2023-09-23',
    '28'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '456', 
    'alysha', 
    'f', 
    '2007-05-12', 
    'Cancer du sein de la femme',
    '2021-12-26',
    '972'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '457', 
    'alyson', 
    'f', 
    '1993-01-26', 
    'Diabète',
    '2021-11-12',
    '06'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '458', 
    'alyssa', 
    'f', 
    '1985-03-04', 
    'Maladie de Parkinson',
    '2021-05-12',
    '91'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '459', 
    'alyssia', 
    'f', 
    '1944-12-20', 
    'Maladies inflammatoires chroniques',
    '2022-03-10',
    '35'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '460', 
    'alyusha', 
    'm', 
    '1976-12-12', 
    'Cancer de la prostate',
    '2023-07-17',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '461', 
    'alyx', 
    'f', 
    '1956-05-13', 
    'Troubles psychotiques',
    '2023-02-12',
    '65'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '462', 
    'alzbeta', 
    'f', 
    '1996-01-17', 
    'Embolie pulmonaire',
    '2021-09-10',
    '64'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '463', 
    'ama', 
    'f', 
    '1981-04-16', 
    'Troubles psychotiques',
    '2021-09-17',
    '71'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '464', 
    'amabel', 
    'f', 
    '1972-02-19', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-07-01',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '465', 
    'amada', 
    'f', 
    '1958-09-14', 
    'Embolie pulmonaire',
    '2023-04-17',
    '89'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '466', 
    'amadeo', 
    'm', 
    '1937-02-02', 
    'Polyarthrite rhumatoïde ',
    '2022-03-06',
    '85'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '467', 
    'amadeus', 
    'm', 
    '1975-07-14', 
    'Maladie de Parkinson',
    '2022-01-01',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '468', 
    'amadi (1)', 
    'f', 
    '1962-09-24', 
    'Troubles addictifs',
    '2021-10-27',
    '971'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '469', 
    'amadi (2)', 
    'm', 
    '1926-10-07', 
    'Polyarthrite rhumatoïde ',
    '2022-05-05',
    '11'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '470', 
    'amal (1)', 
    'f', 
    '1953-08-03', 
    'Accident vasculaire cérébral',
    '2022-03-31',
    '50'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '471', 
    'amal (2)', 
    'm', 
    '1993-07-10', 
    'Cancer de la prostate',
    '2023-07-21',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '472', 
    'amala', 
    'f', 
    '2001-01-24', 
    'Myopathie ou myasthénie',
    '2022-07-21',
    '14'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '473', 
    'amália', 
    'f', 
    '1982-10-08', 
    'Embolie pulmonaire',
    '2021-01-29',
    '39'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '474', 
    'amalia', 
    'f', 
    '1979-11-10', 
    'Insuffisance cardiaque',
    '2021-04-12',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '475', 
    'amalric', 
    'm', 
    '1925-01-09', 
    'Embolie pulmonaire',
    '2021-02-15',
    '84'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '476', 
    'amalthea', 
    'f', 
    '1985-10-13', 
    'Cancer de la prostate',
    '2022-02-02',
    '65'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '477', 
    'amanda', 
    'f', 
    '1992-11-26', 
    'Myopathie ou myasthénie',
    '2023-10-08',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '478', 
    'amandine', 
    'f', 
    '2012-07-16', 
    'Polyarthrite rhumatoïde ',
    '2023-06-28',
    '70'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '479', 
    'amando', 
    'm', 
    '1932-08-03', 
    'Insuffisance cardiaque',
    '2023-11-29',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '480', 
    'amani', 
    'f', 
    '1993-07-24', 
    'Troubles addictifs',
    '2023-01-06',
    '48'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '481', 
    'amar', 
    'm', 
    '1989-03-25', 
    'Embolie pulmonaire',
    '2023-03-10',
    '02'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '482', 
    'amara', 
    'f', 
    '1972-01-01', 
    'Maladies rares',
    '2022-09-20',
    '86'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '483', 
    'amaranta', 
    'f', 
    '2005-07-24', 
    'Polyarthrite rhumatoïde ',
    '2023-05-03',
    '34'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '484', 
    'amarante', 
    'f', 
    '2019-12-02', 
    'Maladies inflammatoires chroniques',
    '2021-09-20',
    '57'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '485', 
    'amardad', 
    'm', 
    '1931-12-17', 
    'Maladies rares',
    '2021-02-28',
    '81'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '486', 
    'amariah', 
    'm', 
    '1976-12-31', 
    'Mucoviscidose',
    '2022-02-11',
    '93'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '487', 
    'amaryllis', 
    'f', 
    '1968-09-09', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2021-05-08',
    '29'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '488', 
    'amaterasu', 
    'f', 
    '1935-06-04', 
    'Cancer du sein de la femme',
    '2022-08-27',
    '74'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '489', 
    'amato', 
    'm', 
    '1988-06-24', 
    'Maladie de Parkinson',
    '2022-03-07',
    '974'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '490', 
    'amaury', 
    'm', 
    '1967-10-17', 
    'Accident vasculaire cérébral',
    '2022-11-30',
    '972'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '491', 
    'amaya', 
    'f', 
    '1939-12-17', 
    'Maladies métaboliques, héréditaires ou amylose',
    '2023-08-06',
    '51'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '492', 
    'amber', 
    'f', 
    '1978-08-15', 
    'Cancer du sein de la femme',
    '2023-03-14',
    '05'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '493', 
    'ambra', 
    'f', 
    '1984-01-07', 
    'Embolie pulmonaire',
    '2022-06-04',
    '32'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '494', 
    'ambre', 
    'f', 
    '1976-12-16', 
    'Accident vasculaire cérébral',
    '2021-10-26',
    '69'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '495', 
    'ambrogino', 
    'm', 
    '1927-11-12', 
    'Mucoviscidose',
    '2023-03-17',
    '17'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '496', 
    'ambrogio', 
    'm', 
    '2003-03-27', 
    'Maladie de Parkinson',
    '2022-06-03',
    '973'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '497', 
    'ambroise', 
    'm', 
    '1991-01-27', 
    'Cancer du sein de la femme',
    '2021-02-26',
    '55'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '498', 
    'ambrose', 
    'm', 
    '2019-08-26', 
    'Cancer colorectal',
    '2023-06-05',
    '73'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '499', 
    'ambrosia', 
    'f', 
    '1941-10-27', 
    'Mucoviscidose',
    '2022-11-18',
    '58'
);
        

INSERT INTO patients_pathologie_dept (id, prenom, sexe, date_naissance, pathologie_nom, pathologie_date, dept)
VALUES (
    '500', 
    'ambrosine', 
    'f', 
    '2007-04-19', 
    'Maladie de Parkinson',
    '2023-10-04',
    '973'
);
        
